// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module horn_schunck_hls_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        u_load,
        v_load,
        i,
        Ix_address0,
        Ix_ce0,
        Ix_q0,
        Iy_address0,
        Iy_ce0,
        Iy_q0,
        It_address0,
        It_ce0,
        It_q0,
        add_ln20,
        u_address0,
        u_ce0,
        u_q0,
        u_address1,
        u_ce1,
        u_we1,
        u_d1,
        u_q1,
        add_ln21,
        v_address0,
        v_ce0,
        v_q0,
        v_address1,
        v_ce1,
        v_we1,
        v_d1,
        v_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 47'd1;
parameter    ap_ST_fsm_pp0_stage1 = 47'd2;
parameter    ap_ST_fsm_pp0_stage2 = 47'd4;
parameter    ap_ST_fsm_pp0_stage3 = 47'd8;
parameter    ap_ST_fsm_pp0_stage4 = 47'd16;
parameter    ap_ST_fsm_pp0_stage5 = 47'd32;
parameter    ap_ST_fsm_pp0_stage6 = 47'd64;
parameter    ap_ST_fsm_pp0_stage7 = 47'd128;
parameter    ap_ST_fsm_pp0_stage8 = 47'd256;
parameter    ap_ST_fsm_pp0_stage9 = 47'd512;
parameter    ap_ST_fsm_pp0_stage10 = 47'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 47'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 47'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 47'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 47'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 47'd32768;
parameter    ap_ST_fsm_pp0_stage16 = 47'd65536;
parameter    ap_ST_fsm_pp0_stage17 = 47'd131072;
parameter    ap_ST_fsm_pp0_stage18 = 47'd262144;
parameter    ap_ST_fsm_pp0_stage19 = 47'd524288;
parameter    ap_ST_fsm_pp0_stage20 = 47'd1048576;
parameter    ap_ST_fsm_pp0_stage21 = 47'd2097152;
parameter    ap_ST_fsm_pp0_stage22 = 47'd4194304;
parameter    ap_ST_fsm_pp0_stage23 = 47'd8388608;
parameter    ap_ST_fsm_pp0_stage24 = 47'd16777216;
parameter    ap_ST_fsm_pp0_stage25 = 47'd33554432;
parameter    ap_ST_fsm_pp0_stage26 = 47'd67108864;
parameter    ap_ST_fsm_pp0_stage27 = 47'd134217728;
parameter    ap_ST_fsm_pp0_stage28 = 47'd268435456;
parameter    ap_ST_fsm_pp0_stage29 = 47'd536870912;
parameter    ap_ST_fsm_pp0_stage30 = 47'd1073741824;
parameter    ap_ST_fsm_pp0_stage31 = 47'd2147483648;
parameter    ap_ST_fsm_pp0_stage32 = 47'd4294967296;
parameter    ap_ST_fsm_pp0_stage33 = 47'd8589934592;
parameter    ap_ST_fsm_pp0_stage34 = 47'd17179869184;
parameter    ap_ST_fsm_pp0_stage35 = 47'd34359738368;
parameter    ap_ST_fsm_pp0_stage36 = 47'd68719476736;
parameter    ap_ST_fsm_pp0_stage37 = 47'd137438953472;
parameter    ap_ST_fsm_pp0_stage38 = 47'd274877906944;
parameter    ap_ST_fsm_pp0_stage39 = 47'd549755813888;
parameter    ap_ST_fsm_pp0_stage40 = 47'd1099511627776;
parameter    ap_ST_fsm_pp0_stage41 = 47'd2199023255552;
parameter    ap_ST_fsm_pp0_stage42 = 47'd4398046511104;
parameter    ap_ST_fsm_pp0_stage43 = 47'd8796093022208;
parameter    ap_ST_fsm_pp0_stage44 = 47'd17592186044416;
parameter    ap_ST_fsm_pp0_stage45 = 47'd35184372088832;
parameter    ap_ST_fsm_pp0_stage46 = 47'd70368744177664;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] u_load;
input  [15:0] v_load;
input  [5:0] i;
output  [11:0] Ix_address0;
output   Ix_ce0;
input  [15:0] Ix_q0;
output  [11:0] Iy_address0;
output   Iy_ce0;
input  [15:0] Iy_q0;
output  [11:0] It_address0;
output   It_ce0;
input  [15:0] It_q0;
input  [5:0] add_ln20;
output  [11:0] u_address0;
output   u_ce0;
input  [15:0] u_q0;
output  [11:0] u_address1;
output   u_ce1;
output   u_we1;
output  [15:0] u_d1;
input  [15:0] u_q1;
input  [5:0] add_ln21;
output  [11:0] v_address0;
output   v_ce0;
input  [15:0] v_q0;
output  [11:0] v_address1;
output   v_ce1;
output   v_we1;
output  [15:0] v_d1;
input  [15:0] v_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [46:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln13_reg_646;
reg    ap_condition_exit_pp0_iter0_stage5;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage46;
wire    ap_block_pp0_stage46_subdone;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] j_1_reg_641;
wire   [0:0] icmp_ln13_fu_255_p2;
wire   [63:0] zext_ln32_fu_269_p1;
reg   [63:0] zext_ln32_reg_650;
reg   [63:0] zext_ln32_reg_650_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [15:0] u1_reg_701;
reg   [15:0] u2_reg_706;
reg   [15:0] v1_reg_711;
reg   [15:0] v2_reg_716;
reg  signed [15:0] Ix_load_reg_721;
wire  signed [27:0] sext_ln32_1_fu_327_p1;
reg  signed [27:0] sext_ln32_1_reg_726;
reg  signed [15:0] Iy_load_reg_733;
reg   [15:0] It_load_reg_739;
reg   [15:0] u3_reg_744;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [15:0] v3_reg_749;
wire  signed [27:0] sext_ln32_5_fu_331_p1;
reg  signed [27:0] sext_ln32_5_reg_754;
wire  signed [27:0] grp_fu_583_p3;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire  signed [15:0] u_bar_fu_375_p4;
reg  signed [15:0] u_bar_reg_766;
wire    ap_block_pp0_stage5_11001;
wire  signed [15:0] v_bar_fu_420_p4;
reg  signed [15:0] v_bar_reg_771;
wire  signed [43:0] sext_ln37_1_fu_487_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln20_fu_284_p1;
wire   [63:0] zext_ln19_fu_304_p1;
wire   [63:0] zext_ln21_fu_321_p1;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage5;
reg   [5:0] j_fu_74;
wire   [5:0] add_ln19_fu_290_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_1;
reg   [15:0] v0_fu_78;
reg   [15:0] ap_sig_allocacmp_v0_load;
reg   [15:0] u0_fu_82;
reg   [15:0] ap_sig_allocacmp_u0_load;
reg    u_ce1_local;
reg   [11:0] u_address1_local;
reg    u_ce0_local;
reg   [11:0] u_address0_local;
reg    u_we1_local;
reg    v_ce1_local;
reg   [11:0] v_address1_local;
reg    v_ce0_local;
reg   [11:0] v_address0_local;
reg    v_we1_local;
reg    Ix_ce0_local;
reg    Iy_ce0_local;
reg    It_ce0_local;
wire   [11:0] tmp_1_fu_261_p3;
wire   [11:0] tmp_2_fu_276_p3;
wire   [11:0] tmp_4_fu_296_p3;
wire   [11:0] tmp_3_fu_315_p3;
wire  signed [15:0] sext_ln32_1_fu_327_p0;
wire    ap_block_pp0_stage2;
wire  signed [15:0] sext_ln29_fu_340_p0;
wire  signed [16:0] sext_ln29_1_fu_344_p1;
wire  signed [16:0] sext_ln29_fu_340_p1;
wire   [16:0] add_ln29_fu_347_p2;
wire  signed [17:0] sext_ln29_4_fu_360_p1;
wire  signed [17:0] sext_ln29_3_fu_357_p1;
wire   [17:0] add_ln29_1_fu_363_p2;
wire  signed [17:0] sext_ln29_2_fu_353_p1;
wire   [17:0] add_ln29_2_fu_369_p2;
wire  signed [15:0] sext_ln30_fu_385_p0;
wire  signed [16:0] sext_ln30_1_fu_389_p1;
wire  signed [16:0] sext_ln30_fu_385_p1;
wire   [16:0] add_ln30_fu_392_p2;
wire  signed [17:0] sext_ln30_4_fu_405_p1;
wire  signed [17:0] sext_ln30_3_fu_402_p1;
wire   [17:0] add_ln30_1_fu_408_p2;
wire  signed [17:0] sext_ln30_2_fu_398_p1;
wire   [17:0] add_ln30_2_fu_414_p2;
wire  signed [27:0] grp_fu_607_p3;
wire  signed [27:0] grp_fu_591_p3;
wire   [15:0] P_fu_451_p4;
wire  signed [15:0] mul_ln37_fu_473_p0;
wire  signed [31:0] sext_ln37_fu_469_p1;
wire   [31:0] mul_ln37_fu_473_p2;
wire   [15:0] D_fu_460_p4;
wire   [43:0] grp_fu_491_p0;
wire  signed [15:0] grp_fu_491_p1;
wire  signed [15:0] mul_ln38_fu_497_p0;
wire   [31:0] mul_ln38_fu_497_p2;
wire   [43:0] grp_fu_511_p0;
wire  signed [15:0] grp_fu_511_p1;
wire   [27:0] grp_fu_491_p2;
wire   [27:0] shl_ln37_1_fu_517_p3;
wire   [27:0] trunc_ln37_fu_524_p1;
wire   [27:0] sub_ln37_fu_528_p2;
wire   [27:0] grp_fu_511_p2;
wire   [27:0] shl_ln38_1_fu_545_p3;
wire   [27:0] trunc_ln38_fu_552_p1;
wire   [27:0] sub_ln38_fu_556_p2;
wire  signed [15:0] grp_fu_583_p0;
wire  signed [15:0] grp_fu_583_p1;
wire   [24:0] grp_fu_583_p2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire  signed [15:0] grp_fu_591_p0;
wire  signed [15:0] grp_fu_591_p1;
wire    ap_block_pp0_stage4;
wire  signed [15:0] grp_fu_600_p0;
wire  signed [27:0] grp_fu_600_p2;
wire  signed [15:0] grp_fu_607_p1;
wire  signed [27:0] grp_fu_600_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [46:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_block_pp0_stage14_subdone;
wire    ap_block_pp0_stage15_subdone;
wire    ap_block_pp0_stage16_subdone;
wire    ap_block_pp0_stage17_subdone;
wire    ap_block_pp0_stage18_subdone;
wire    ap_block_pp0_stage19_subdone;
wire    ap_block_pp0_stage20_subdone;
wire    ap_block_pp0_stage21_subdone;
wire    ap_block_pp0_stage22_subdone;
wire    ap_block_pp0_stage23_subdone;
wire    ap_block_pp0_stage24_subdone;
wire    ap_block_pp0_stage25_subdone;
wire    ap_block_pp0_stage26_subdone;
wire    ap_block_pp0_stage27_subdone;
wire    ap_block_pp0_stage28_subdone;
wire    ap_block_pp0_stage29_subdone;
wire    ap_block_pp0_stage30_subdone;
wire    ap_block_pp0_stage31_subdone;
wire    ap_block_pp0_stage32_subdone;
wire    ap_block_pp0_stage33_subdone;
wire    ap_block_pp0_stage34_subdone;
wire    ap_block_pp0_stage35_subdone;
wire    ap_block_pp0_stage36_subdone;
wire    ap_block_pp0_stage37_subdone;
wire    ap_block_pp0_stage38_subdone;
wire    ap_block_pp0_stage39_subdone;
wire    ap_block_pp0_stage40_subdone;
wire    ap_block_pp0_stage41_subdone;
wire    ap_block_pp0_stage42_subdone;
wire    ap_block_pp0_stage43_subdone;
wire    ap_block_pp0_stage44_subdone;
wire    ap_block_pp0_stage45_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 47'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 j_fu_74 = 6'd0;
#0 v0_fu_78 = 16'd0;
#0 u0_fu_82 = 16'd0;
#0 ap_done_reg = 1'b0;
end

horn_schunck_hls_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U1(
    .din0(mul_ln37_fu_473_p0),
    .din1(Ix_load_reg_721),
    .dout(mul_ln37_fu_473_p2)
);

horn_schunck_hls_sdiv_44ns_16s_28_48_1 #(
    .ID( 1 ),
    .NUM_STAGE( 48 ),
    .din0_WIDTH( 44 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
sdiv_44ns_16s_28_48_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_491_p0),
    .din1(grp_fu_491_p1),
    .ce(1'b1),
    .dout(grp_fu_491_p2)
);

horn_schunck_hls_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U3(
    .din0(mul_ln38_fu_497_p0),
    .din1(Iy_load_reg_733),
    .dout(mul_ln38_fu_497_p2)
);

horn_schunck_hls_sdiv_44ns_16s_28_48_1 #(
    .ID( 1 ),
    .NUM_STAGE( 48 ),
    .din0_WIDTH( 44 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
sdiv_44ns_16s_28_48_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_511_p0),
    .din1(grp_fu_511_p1),
    .ce(1'b1),
    .dout(grp_fu_511_p2)
);

horn_schunck_hls_mac_muladd_16s_16s_25ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_16s_25ns_28_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_583_p0),
    .din1(grp_fu_583_p1),
    .din2(grp_fu_583_p2),
    .ce(1'b1),
    .dout(grp_fu_583_p3)
);

horn_schunck_hls_mac_muladd_16s_16s_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_16s_28s_28_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_591_p0),
    .din1(grp_fu_591_p1),
    .din2(grp_fu_583_p3),
    .ce(1'b1),
    .dout(grp_fu_591_p3)
);

horn_schunck_hls_mac_muladd_16s_16s_28s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_16s_28s_28_1_1_U7(
    .din0(grp_fu_600_p0),
    .din1(u_bar_fu_375_p4),
    .din2(grp_fu_600_p2),
    .dout(grp_fu_600_p3)
);

horn_schunck_hls_mac_muladd_16s_16s_28s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_16s_28s_28_1_1_U8(
    .din0(v_bar_fu_420_p4),
    .din1(grp_fu_607_p1),
    .din2(grp_fu_600_p3),
    .dout(grp_fu_607_p3)
);

horn_schunck_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage5),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage5)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage46_subdone) & (1'b1 == ap_CS_fsm_pp0_stage46))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln13_fu_255_p2 == 1'd0))) begin
            j_fu_74 <= add_ln19_fu_290_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_74 <= 6'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u0_fu_82 <= u_load;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        u0_fu_82 <= {{sub_ln37_fu_528_p2[27:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v0_fu_78 <= v_load;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        v0_fu_78 <= {{sub_ln38_fu_556_p2[27:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        It_load_reg_739 <= It_q0;
        Ix_load_reg_721 <= Ix_q0;
        Iy_load_reg_733 <= Iy_q0;
        sext_ln32_1_reg_726 <= sext_ln32_1_fu_327_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln13_reg_646 <= icmp_ln13_fu_255_p2;
        j_1_reg_641 <= ap_sig_allocacmp_j_1;
        zext_ln32_reg_650[11 : 0] <= zext_ln32_fu_269_p1[11 : 0];
        zext_ln32_reg_650_pp0_iter1_reg[11 : 0] <= zext_ln32_reg_650[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sext_ln32_5_reg_754 <= sext_ln32_5_fu_331_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        u1_reg_701 <= u_q1;
        u2_reg_706 <= u_q0;
        v1_reg_711 <= v_q1;
        v2_reg_716 <= v_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        u3_reg_744 <= u_q0;
        v3_reg_749 <= v_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        u_bar_reg_766 <= {{add_ln29_2_fu_369_p2[17:2]}};
        v_bar_reg_771 <= {{add_ln30_2_fu_414_p2[17:2]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        It_ce0_local = 1'b1;
    end else begin
        It_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Ix_ce0_local = 1'b1;
    end else begin
        Ix_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Iy_ce0_local = 1'b1;
    end else begin
        Iy_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_646 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage46_subdone) & (1'b1 == ap_CS_fsm_pp0_stage46))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 6'd1;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_sig_allocacmp_u0_load = {{sub_ln37_fu_528_p2[27:12]}};
    end else begin
        ap_sig_allocacmp_u0_load = u0_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_sig_allocacmp_v0_load = {{sub_ln38_fu_556_p2[27:12]}};
    end else begin
        ap_sig_allocacmp_v0_load = v0_fu_78;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        u_address0_local = zext_ln21_fu_321_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_address0_local = zext_ln20_fu_284_p1;
    end else begin
        u_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        u_address1_local = zext_ln32_reg_650_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_address1_local = zext_ln19_fu_304_p1;
    end else begin
        u_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        u_ce0_local = 1'b1;
    end else begin
        u_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        u_ce1_local = 1'b1;
    end else begin
        u_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        u_we1_local = 1'b1;
    end else begin
        u_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        v_address0_local = zext_ln21_fu_321_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_address0_local = zext_ln20_fu_284_p1;
    end else begin
        v_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        v_address1_local = zext_ln32_reg_650_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_address1_local = zext_ln19_fu_304_p1;
    end else begin
        v_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        v_ce0_local = 1'b1;
    end else begin
        v_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        v_ce1_local = 1'b1;
    end else begin
        v_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        v_we1_local = 1'b1;
    end else begin
        v_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage5)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        ap_ST_fsm_pp0_stage16 : begin
            if ((1'b0 == ap_block_pp0_stage16_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end
        end
        ap_ST_fsm_pp0_stage17 : begin
            if ((1'b0 == ap_block_pp0_stage17_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end
        end
        ap_ST_fsm_pp0_stage18 : begin
            if ((1'b0 == ap_block_pp0_stage18_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end
        end
        ap_ST_fsm_pp0_stage19 : begin
            if ((1'b0 == ap_block_pp0_stage19_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end
        end
        ap_ST_fsm_pp0_stage20 : begin
            if ((1'b0 == ap_block_pp0_stage20_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage20;
            end
        end
        ap_ST_fsm_pp0_stage21 : begin
            if ((1'b0 == ap_block_pp0_stage21_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage21;
            end
        end
        ap_ST_fsm_pp0_stage22 : begin
            if ((1'b0 == ap_block_pp0_stage22_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage22;
            end
        end
        ap_ST_fsm_pp0_stage23 : begin
            if ((1'b0 == ap_block_pp0_stage23_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage23;
            end
        end
        ap_ST_fsm_pp0_stage24 : begin
            if ((1'b0 == ap_block_pp0_stage24_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage24;
            end
        end
        ap_ST_fsm_pp0_stage25 : begin
            if ((1'b0 == ap_block_pp0_stage25_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage25;
            end
        end
        ap_ST_fsm_pp0_stage26 : begin
            if ((1'b0 == ap_block_pp0_stage26_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage26;
            end
        end
        ap_ST_fsm_pp0_stage27 : begin
            if ((1'b0 == ap_block_pp0_stage27_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage27;
            end
        end
        ap_ST_fsm_pp0_stage28 : begin
            if ((1'b0 == ap_block_pp0_stage28_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage28;
            end
        end
        ap_ST_fsm_pp0_stage29 : begin
            if ((1'b0 == ap_block_pp0_stage29_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage29;
            end
        end
        ap_ST_fsm_pp0_stage30 : begin
            if ((1'b0 == ap_block_pp0_stage30_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage30;
            end
        end
        ap_ST_fsm_pp0_stage31 : begin
            if ((1'b0 == ap_block_pp0_stage31_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage31;
            end
        end
        ap_ST_fsm_pp0_stage32 : begin
            if ((1'b0 == ap_block_pp0_stage32_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage32;
            end
        end
        ap_ST_fsm_pp0_stage33 : begin
            if ((1'b0 == ap_block_pp0_stage33_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage33;
            end
        end
        ap_ST_fsm_pp0_stage34 : begin
            if ((1'b0 == ap_block_pp0_stage34_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage34;
            end
        end
        ap_ST_fsm_pp0_stage35 : begin
            if ((1'b0 == ap_block_pp0_stage35_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage35;
            end
        end
        ap_ST_fsm_pp0_stage36 : begin
            if ((1'b0 == ap_block_pp0_stage36_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage36;
            end
        end
        ap_ST_fsm_pp0_stage37 : begin
            if ((1'b0 == ap_block_pp0_stage37_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage37;
            end
        end
        ap_ST_fsm_pp0_stage38 : begin
            if ((1'b0 == ap_block_pp0_stage38_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage38;
            end
        end
        ap_ST_fsm_pp0_stage39 : begin
            if ((1'b0 == ap_block_pp0_stage39_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage39;
            end
        end
        ap_ST_fsm_pp0_stage40 : begin
            if ((1'b0 == ap_block_pp0_stage40_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage40;
            end
        end
        ap_ST_fsm_pp0_stage41 : begin
            if ((1'b0 == ap_block_pp0_stage41_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage41;
            end
        end
        ap_ST_fsm_pp0_stage42 : begin
            if ((1'b0 == ap_block_pp0_stage42_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage42;
            end
        end
        ap_ST_fsm_pp0_stage43 : begin
            if ((1'b0 == ap_block_pp0_stage43_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage43;
            end
        end
        ap_ST_fsm_pp0_stage44 : begin
            if ((1'b0 == ap_block_pp0_stage44_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage45;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage44;
            end
        end
        ap_ST_fsm_pp0_stage45 : begin
            if ((1'b0 == ap_block_pp0_stage45_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage46;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage45;
            end
        end
        ap_ST_fsm_pp0_stage46 : begin
            if ((1'b0 == ap_block_pp0_stage46_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage46;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign D_fu_460_p4 = {{grp_fu_591_p3[27:12]}};

assign It_address0 = zext_ln32_fu_269_p1;

assign It_ce0 = It_ce0_local;

assign Ix_address0 = zext_ln32_fu_269_p1;

assign Ix_ce0 = Ix_ce0_local;

assign Iy_address0 = zext_ln32_fu_269_p1;

assign Iy_ce0 = Iy_ce0_local;

assign P_fu_451_p4 = {{grp_fu_607_p3[27:12]}};

assign add_ln19_fu_290_p2 = (ap_sig_allocacmp_j_1 + 6'd1);

assign add_ln29_1_fu_363_p2 = ($signed(sext_ln29_4_fu_360_p1) + $signed(sext_ln29_3_fu_357_p1));

assign add_ln29_2_fu_369_p2 = ($signed(add_ln29_1_fu_363_p2) + $signed(sext_ln29_2_fu_353_p1));

assign add_ln29_fu_347_p2 = ($signed(sext_ln29_1_fu_344_p1) + $signed(sext_ln29_fu_340_p1));

assign add_ln30_1_fu_408_p2 = ($signed(sext_ln30_4_fu_405_p1) + $signed(sext_ln30_3_fu_402_p1));

assign add_ln30_2_fu_414_p2 = ($signed(add_ln30_1_fu_408_p2) + $signed(sext_ln30_2_fu_398_p1));

assign add_ln30_fu_392_p2 = ($signed(sext_ln30_1_fu_389_p1) + $signed(sext_ln30_fu_385_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage46 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage17_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage19_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage20_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage21_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage22_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage23_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage24_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage25_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage26_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage27_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage28_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage29_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage30_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage31_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage32_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage33_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage34_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage35_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage36_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage37_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage38_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage39_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage40_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage41_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage42_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage43_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage44_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage45_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage46_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage5;

assign ap_ready = ap_ready_sig;

assign grp_fu_491_p0 = {{mul_ln37_fu_473_p2}, {12'd0}};

assign grp_fu_491_p1 = sext_ln37_1_fu_487_p1;

assign grp_fu_511_p0 = {{mul_ln38_fu_497_p2}, {12'd0}};

assign grp_fu_511_p1 = sext_ln37_1_fu_487_p1;

assign grp_fu_583_p0 = sext_ln32_1_fu_327_p1;

assign grp_fu_583_p1 = sext_ln32_1_fu_327_p1;

assign grp_fu_583_p2 = 28'd16777216;

assign grp_fu_591_p0 = sext_ln32_5_fu_331_p1;

assign grp_fu_591_p1 = sext_ln32_5_fu_331_p1;

assign grp_fu_600_p0 = sext_ln32_1_reg_726;

assign grp_fu_600_p2 = {{It_load_reg_739}, {12'd0}};

assign grp_fu_607_p1 = sext_ln32_5_reg_754;

assign icmp_ln13_fu_255_p2 = ((ap_sig_allocacmp_j_1 == 6'd63) ? 1'b1 : 1'b0);

assign mul_ln37_fu_473_p0 = sext_ln37_fu_469_p1;

assign mul_ln38_fu_497_p0 = sext_ln37_fu_469_p1;

assign sext_ln29_1_fu_344_p1 = $signed(u1_reg_701);

assign sext_ln29_2_fu_353_p1 = $signed(add_ln29_fu_347_p2);

assign sext_ln29_3_fu_357_p1 = $signed(u2_reg_706);

assign sext_ln29_4_fu_360_p1 = $signed(u3_reg_744);

assign sext_ln29_fu_340_p0 = ap_sig_allocacmp_u0_load;

assign sext_ln29_fu_340_p1 = sext_ln29_fu_340_p0;

assign sext_ln30_1_fu_389_p1 = $signed(v1_reg_711);

assign sext_ln30_2_fu_398_p1 = $signed(add_ln30_fu_392_p2);

assign sext_ln30_3_fu_402_p1 = $signed(v2_reg_716);

assign sext_ln30_4_fu_405_p1 = $signed(v3_reg_749);

assign sext_ln30_fu_385_p0 = ap_sig_allocacmp_v0_load;

assign sext_ln30_fu_385_p1 = sext_ln30_fu_385_p0;

assign sext_ln32_1_fu_327_p0 = Ix_q0;

assign sext_ln32_1_fu_327_p1 = sext_ln32_1_fu_327_p0;

assign sext_ln32_5_fu_331_p1 = Iy_load_reg_733;

assign sext_ln37_1_fu_487_p1 = $signed(D_fu_460_p4);

assign sext_ln37_fu_469_p1 = $signed(P_fu_451_p4);

assign shl_ln37_1_fu_517_p3 = {{u_bar_reg_766}, {12'd0}};

assign shl_ln38_1_fu_545_p3 = {{v_bar_reg_771}, {12'd0}};

assign sub_ln37_fu_528_p2 = (shl_ln37_1_fu_517_p3 - trunc_ln37_fu_524_p1);

assign sub_ln38_fu_556_p2 = (shl_ln38_1_fu_545_p3 - trunc_ln38_fu_552_p1);

assign tmp_1_fu_261_p3 = {{i}, {ap_sig_allocacmp_j_1}};

assign tmp_2_fu_276_p3 = {{add_ln20}, {ap_sig_allocacmp_j_1}};

assign tmp_3_fu_315_p3 = {{add_ln21}, {j_1_reg_641}};

assign tmp_4_fu_296_p3 = {{i}, {add_ln19_fu_290_p2}};

assign trunc_ln37_fu_524_p1 = grp_fu_491_p2[27:0];

assign trunc_ln38_fu_552_p1 = grp_fu_511_p2[27:0];

assign u_address0 = u_address0_local;

assign u_address1 = u_address1_local;

assign u_bar_fu_375_p4 = {{add_ln29_2_fu_369_p2[17:2]}};

assign u_ce0 = u_ce0_local;

assign u_ce1 = u_ce1_local;

assign u_d1 = {{sub_ln37_fu_528_p2[27:12]}};

assign u_we1 = u_we1_local;

assign v_address0 = v_address0_local;

assign v_address1 = v_address1_local;

assign v_bar_fu_420_p4 = {{add_ln30_2_fu_414_p2[17:2]}};

assign v_ce0 = v_ce0_local;

assign v_ce1 = v_ce1_local;

assign v_d1 = {{sub_ln38_fu_556_p2[27:12]}};

assign v_we1 = v_we1_local;

assign zext_ln19_fu_304_p1 = tmp_4_fu_296_p3;

assign zext_ln20_fu_284_p1 = tmp_2_fu_276_p3;

assign zext_ln21_fu_321_p1 = tmp_3_fu_315_p3;

assign zext_ln32_fu_269_p1 = tmp_1_fu_261_p3;

always @ (posedge ap_clk) begin
    zext_ln32_reg_650[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_650_pp0_iter1_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //horn_schunck_hls_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3
