

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1"],
		"CDFG" : "horn_schunck_hls",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1813521", "EstimateLatencyMax" : "1813521",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "Ix", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100", "Port" : "Ix", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "Iy", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100", "Port" : "Iy", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "It", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100", "Port" : "It", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "u", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100", "Port" : "u", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "v", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100", "Port" : "v", "Inst_start_state" : "5", "Inst_end_state" : "6"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_12_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "6", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state6"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_11_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "6", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6", "7", "8", "9", "10"],
		"CDFG" : "horn_schunck_hls_Pipeline_VITIS_LOOP_13_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2921", "EstimateLatencyMax" : "2921",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "u_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "v_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "i", "Type" : "None", "Direction" : "I"},
			{"Name" : "Ix", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "Iy", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "It", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "add_ln20", "Type" : "None", "Direction" : "I"},
			{"Name" : "u", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "add_ln21", "Type" : "None", "Direction" : "I"},
			{"Name" : "v", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_13_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "47", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage5", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage5_subdone", "QuitState" : "ap_ST_fsm_pp0_stage5", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage5_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100.mul_16s_16s_32_1_1_U1", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100.sdiv_44ns_16s_28_48_1_U2", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100.mul_16s_16s_32_1_1_U3", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100.sdiv_44ns_16s_28_48_1_U4", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100.mac_muladd_16s_16s_25ns_28_4_1_U5", "Parent" : "1"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100.mac_muladd_16s_16s_28s_28_4_1_U6", "Parent" : "1"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100.mac_muladd_16s_16s_28s_28_1_1_U7", "Parent" : "1"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100.mac_muladd_16s_16s_28s_28_1_1_U8", "Parent" : "1"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_horn_schunck_hls_Pipeline_VITIS_LOOP_13_3_fu_100.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"}]}
