-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pyramidal_hs_compute_derivatives is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    img1_ce0 : OUT STD_LOGIC;
    img1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    img1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    img1_ce1 : OUT STD_LOGIC;
    img1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    img2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    img2_ce0 : OUT STD_LOGIC;
    img2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    Ix64_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    Ix64_ce0 : OUT STD_LOGIC;
    Ix64_we0 : OUT STD_LOGIC;
    Ix64_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    Iy64_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    Iy64_ce0 : OUT STD_LOGIC;
    Iy64_we0 : OUT STD_LOGIC;
    Iy64_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    It64_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    It64_ce0 : OUT STD_LOGIC;
    It64_we0 : OUT STD_LOGIC;
    It64_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of pyramidal_hs_compute_derivatives is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_3F : STD_LOGIC_VECTOR (6 downto 0) := "0111111";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln12_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln12_reg_610 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal It64_addr_reg_614 : STD_LOGIC_VECTOR (11 downto 0);
    signal Ix64_addr_reg_619 : STD_LOGIC_VECTOR (11 downto 0);
    signal Iy64_addr_reg_624 : STD_LOGIC_VECTOR (11 downto 0);
    signal img1_addr_5_reg_629 : STD_LOGIC_VECTOR (11 downto 0);
    signal img1_addr_6_reg_634 : STD_LOGIC_VECTOR (11 downto 0);
    signal img1_addr_7_reg_639 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln19_2_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_2_reg_649 : STD_LOGIC_VECTOR (0 downto 0);
    signal img2_load_reg_663 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_phi_mux_storemerge_phi_fu_183_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln32_fu_583_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal zext_ln32_3_fu_333_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln29_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_1_fu_359_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln28_fu_412_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln28_1_fu_431_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_68 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln13_fu_436_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_load : STD_LOGIC_VECTOR (6 downto 0);
    signal y_fu_72 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln12_1_fu_261_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_y_load : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_fu_76 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal add_ln12_fu_215_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (12 downto 0);
    signal img1_ce1_local : STD_LOGIC;
    signal img1_address1_local : STD_LOGIC_VECTOR (11 downto 0);
    signal img1_ce0_local : STD_LOGIC;
    signal img1_address0_local : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal img2_ce0_local : STD_LOGIC;
    signal Ix64_we0_local : STD_LOGIC;
    signal Ix64_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal Ix64_ce0_local : STD_LOGIC;
    signal Ix64_address0_local : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln28_fu_511_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Iy64_we0_local : STD_LOGIC;
    signal Iy64_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal Iy64_ce0_local : STD_LOGIC;
    signal Iy64_address0_local : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln29_fu_574_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal It64_we0_local : STD_LOGIC;
    signal It64_ce0_local : STD_LOGIC;
    signal icmp_ln13_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln12_fu_227_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln29_3_fu_251_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln32_fu_269_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln29_fu_245_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln12_1_fu_257_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln29_2_fu_293_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln29_2_fu_309_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln12_fu_237_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_273_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln32_fu_323_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln32_fu_327_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_fu_301_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln29_4_fu_342_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_70_fu_315_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln29_5_fu_353_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln19_1_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln19_3_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln19_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln19_2_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_1_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln13_fu_364_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln28_fu_398_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_71_fu_404_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln28_1_fu_417_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_72_fu_423_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln28_fu_457_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln28_1_fu_461_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln28_fu_465_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln28_1_fu_479_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln28_1_fu_485_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_85_fu_471_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln28_2_fu_505_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln28_2_fu_495_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln29_fu_520_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln29_1_fu_524_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln29_fu_528_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln29_1_fu_542_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln29_1_fu_548_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_86_fu_534_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln29_2_fu_568_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln29_2_fu_558_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pyramidal_hs_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pyramidal_hs_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln12_fu_209_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_76 <= add_ln12_fu_215_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_76 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    x_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln12_fu_209_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_68 <= add_ln13_fu_436_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_68 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    y_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln12_fu_209_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    y_fu_72 <= select_ln12_1_fu_261_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_72 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                It64_addr_reg_614 <= zext_ln32_3_fu_333_p1(12 - 1 downto 0);
                Ix64_addr_reg_619 <= zext_ln32_3_fu_333_p1(12 - 1 downto 0);
                Iy64_addr_reg_624 <= zext_ln32_3_fu_333_p1(12 - 1 downto 0);
                icmp_ln12_reg_610 <= icmp_ln12_fu_209_p2;
                img1_addr_5_reg_629 <= zext_ln29_fu_348_p1(12 - 1 downto 0);
                img1_addr_6_reg_634 <= zext_ln29_1_fu_359_p1(12 - 1 downto 0);
                img1_addr_7_reg_639 <= zext_ln32_3_fu_333_p1(12 - 1 downto 0);
                or_ln19_2_reg_649 <= or_ln19_2_fu_392_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                img2_load_reg_663 <= img2_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage2_subdone, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    It64_address0 <= It64_addr_reg_614;
    It64_ce0 <= It64_ce0_local;

    It64_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            It64_ce0_local <= ap_const_logic_1;
        else 
            It64_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    It64_d0 <= ap_phi_mux_storemerge_phi_fu_183_p4;
    It64_we0 <= It64_we0_local;

    It64_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            It64_we0_local <= ap_const_logic_1;
        else 
            It64_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    Ix64_address0 <= Ix64_address0_local;

    Ix64_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter0_reg, Ix64_addr_reg_619, ap_CS_fsm_pp0_stage1, zext_ln32_3_fu_333_p1, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            Ix64_address0_local <= Ix64_addr_reg_619;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Ix64_address0_local <= zext_ln32_3_fu_333_p1(12 - 1 downto 0);
        else 
            Ix64_address0_local <= "XXXXXXXXXXXX";
        end if; 
    end process;

    Ix64_ce0 <= Ix64_ce0_local;

    Ix64_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            Ix64_ce0_local <= ap_const_logic_1;
        else 
            Ix64_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    Ix64_d0 <= Ix64_d0_local;

    Ix64_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, select_ln28_fu_511_p3)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            Ix64_d0_local <= select_ln28_fu_511_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Ix64_d0_local <= ap_const_lv16_0;
        else 
            Ix64_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    Ix64_we0 <= Ix64_we0_local;

    Ix64_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_209_p2, ap_enable_reg_pp0_iter0_reg, icmp_ln12_reg_610, ap_block_pp0_stage0_11001, or_ln19_2_fu_392_p2, or_ln19_2_reg_649, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((icmp_ln12_fu_209_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln19_2_fu_392_p2 = ap_const_lv1_1)) or ((icmp_ln12_reg_610 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln19_2_reg_649 = ap_const_lv1_0)))) then 
            Ix64_we0_local <= ap_const_logic_1;
        else 
            Ix64_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    Iy64_address0 <= Iy64_address0_local;

    Iy64_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, Iy64_addr_reg_624, zext_ln32_3_fu_333_p1, ap_block_pp0_stage0, ap_block_pp0_stage2)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            Iy64_address0_local <= Iy64_addr_reg_624;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Iy64_address0_local <= zext_ln32_3_fu_333_p1(12 - 1 downto 0);
        else 
            Iy64_address0_local <= "XXXXXXXXXXXX";
        end if; 
    end process;

    Iy64_ce0 <= Iy64_ce0_local;

    Iy64_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            Iy64_ce0_local <= ap_const_logic_1;
        else 
            Iy64_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    Iy64_d0 <= Iy64_d0_local;

    Iy64_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0, ap_block_pp0_stage2, select_ln29_fu_574_p3)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            Iy64_d0_local <= select_ln29_fu_574_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Iy64_d0_local <= ap_const_lv16_0;
        else 
            Iy64_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    Iy64_we0 <= Iy64_we0_local;

    Iy64_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln12_fu_209_p2, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln12_reg_610, ap_block_pp0_stage0_11001, or_ln19_2_fu_392_p2, or_ln19_2_reg_649, ap_block_pp0_stage2_11001)
    begin
        if ((((icmp_ln12_fu_209_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln19_2_fu_392_p2 = ap_const_lv1_1)) or ((icmp_ln12_reg_610 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln19_2_reg_649 = ap_const_lv1_0)))) then 
            Iy64_we0_local <= ap_const_logic_1;
        else 
            Iy64_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln12_fu_215_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv13_1));
    add_ln13_fu_436_p2 <= std_logic_vector(unsigned(select_ln12_fu_237_p3) + unsigned(ap_const_lv7_1));
    add_ln28_1_fu_417_p2 <= std_logic_vector(unsigned(trunc_ln13_fu_364_p1) + unsigned(ap_const_lv6_3F));
    add_ln28_fu_398_p2 <= std_logic_vector(unsigned(trunc_ln13_fu_364_p1) + unsigned(ap_const_lv6_1));
    add_ln29_2_fu_309_p2 <= std_logic_vector(unsigned(trunc_ln32_fu_269_p1) + unsigned(ap_const_lv6_3F));
    add_ln29_3_fu_251_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_y_load) + unsigned(ap_const_lv7_1));
    add_ln29_4_fu_342_p2 <= std_logic_vector(unsigned(tmp_s_fu_301_p3) + unsigned(zext_ln32_fu_323_p1));
    add_ln29_5_fu_353_p2 <= std_logic_vector(unsigned(tmp_70_fu_315_p3) + unsigned(zext_ln32_fu_323_p1));
    add_ln29_fu_245_p2 <= std_logic_vector(unsigned(trunc_ln12_fu_227_p1) + unsigned(ap_const_lv6_2));
    add_ln32_fu_327_p2 <= std_logic_vector(unsigned(tmp_fu_273_p3) + unsigned(zext_ln32_fu_323_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln12_fu_209_p2)
    begin
        if (((icmp_ln12_fu_209_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_storemerge_phi_fu_183_p4_assign_proc : process(icmp_ln12_reg_610, or_ln19_2_reg_649, sub_ln32_fu_583_p2)
    begin
        if (((icmp_ln12_reg_610 = ap_const_lv1_0) and (or_ln19_2_reg_649 = ap_const_lv1_0))) then 
            ap_phi_mux_storemerge_phi_fu_183_p4 <= sub_ln32_fu_583_p2;
        else 
            ap_phi_mux_storemerge_phi_fu_183_p4 <= ap_const_lv16_0;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_x_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_68, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_x_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_x_load <= x_fu_68;
        end if; 
    end process;


    ap_sig_allocacmp_y_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, y_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_y_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_y_load <= y_fu_72;
        end if; 
    end process;

    icmp_ln12_fu_209_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv13_1000) else "0";
    icmp_ln13_fu_231_p2 <= "1" when (ap_sig_allocacmp_x_load = ap_const_lv7_40) else "0";
    icmp_ln19_1_fu_287_p2 <= "1" when (select_ln12_1_fu_261_p3 = ap_const_lv7_3F) else "0";
    icmp_ln19_2_fu_368_p2 <= "1" when (select_ln12_fu_237_p3 = ap_const_lv7_0) else "0";
    icmp_ln19_3_fu_374_p2 <= "1" when (select_ln12_fu_237_p3 = ap_const_lv7_3F) else "0";
    icmp_ln19_fu_281_p2 <= "1" when (select_ln12_1_fu_261_p3 = ap_const_lv7_0) else "0";
    img1_address0 <= img1_address0_local;

    img1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, img1_addr_6_reg_634, img1_addr_7_reg_639, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln28_1_fu_431_p1, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            img1_address0_local <= img1_addr_7_reg_639;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            img1_address0_local <= img1_addr_6_reg_634;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img1_address0_local <= zext_ln28_1_fu_431_p1(12 - 1 downto 0);
        else 
            img1_address0_local <= "XXXXXXXXXXXX";
        end if; 
    end process;

    img1_address1 <= img1_address1_local;

    img1_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter0_reg, img1_addr_5_reg_629, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln28_fu_412_p1, ap_block_pp0_stage1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            img1_address1_local <= img1_addr_5_reg_629;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img1_address1_local <= zext_ln28_fu_412_p1(12 - 1 downto 0);
        else 
            img1_address1_local <= "XXXXXXXXXXXX";
        end if; 
    end process;

    img1_ce0 <= img1_ce0_local;

    img1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            img1_ce0_local <= ap_const_logic_1;
        else 
            img1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img1_ce1 <= img1_ce1_local;

    img1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            img1_ce1_local <= ap_const_logic_1;
        else 
            img1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    img2_address0 <= zext_ln32_3_fu_333_p1(12 - 1 downto 0);
    img2_ce0 <= img2_ce0_local;

    img2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img2_ce0_local <= ap_const_logic_1;
        else 
            img2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln19_1_fu_386_p2 <= (icmp_ln19_fu_281_p2 or icmp_ln19_2_fu_368_p2);
    or_ln19_2_fu_392_p2 <= (or_ln19_fu_380_p2 or or_ln19_1_fu_386_p2);
    or_ln19_fu_380_p2 <= (icmp_ln19_3_fu_374_p2 or icmp_ln19_1_fu_287_p2);
    select_ln12_1_fu_261_p3 <= 
        add_ln29_3_fu_251_p2 when (icmp_ln13_fu_231_p2(0) = '1') else 
        ap_sig_allocacmp_y_load;
    select_ln12_fu_237_p3 <= 
        ap_const_lv7_0 when (icmp_ln13_fu_231_p2(0) = '1') else 
        ap_sig_allocacmp_x_load;
    select_ln28_fu_511_p3 <= 
        sub_ln28_2_fu_505_p2 when (tmp_85_fu_471_p3(0) = '1') else 
        trunc_ln28_2_fu_495_p4;
    select_ln29_2_fu_293_p3 <= 
        add_ln29_fu_245_p2 when (icmp_ln13_fu_231_p2(0) = '1') else 
        trunc_ln12_1_fu_257_p1;
    select_ln29_fu_574_p3 <= 
        sub_ln29_2_fu_568_p2 when (tmp_86_fu_534_p3(0) = '1') else 
        trunc_ln29_2_fu_558_p4;
        sext_ln28_1_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(img1_q0),17));

        sext_ln28_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(img1_q1),17));

        sext_ln29_1_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(img1_q0),17));

        sext_ln29_fu_520_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(img1_q1),17));

    sub_ln28_1_fu_479_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sub_ln28_fu_465_p2));
    sub_ln28_2_fu_505_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(trunc_ln28_1_fu_485_p4));
    sub_ln28_fu_465_p2 <= std_logic_vector(signed(sext_ln28_fu_457_p1) - signed(sext_ln28_1_fu_461_p1));
    sub_ln29_1_fu_542_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sub_ln29_fu_528_p2));
    sub_ln29_2_fu_568_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(trunc_ln29_1_fu_548_p4));
    sub_ln29_fu_528_p2 <= std_logic_vector(signed(sext_ln29_fu_520_p1) - signed(sext_ln29_1_fu_524_p1));
    sub_ln32_fu_583_p2 <= std_logic_vector(unsigned(img2_load_reg_663) - unsigned(img1_q0));
    tmp_70_fu_315_p3 <= (add_ln29_2_fu_309_p2 & ap_const_lv6_0);
    tmp_71_fu_404_p3 <= (trunc_ln32_fu_269_p1 & add_ln28_fu_398_p2);
    tmp_72_fu_423_p3 <= (trunc_ln32_fu_269_p1 & add_ln28_1_fu_417_p2);
    tmp_85_fu_471_p3 <= sub_ln28_fu_465_p2(16 downto 16);
    tmp_86_fu_534_p3 <= sub_ln29_fu_528_p2(16 downto 16);
    tmp_fu_273_p3 <= (trunc_ln32_fu_269_p1 & ap_const_lv6_0);
    tmp_s_fu_301_p3 <= (select_ln29_2_fu_293_p3 & ap_const_lv6_0);
    trunc_ln12_1_fu_257_p1 <= add_ln29_3_fu_251_p2(6 - 1 downto 0);
    trunc_ln12_fu_227_p1 <= ap_sig_allocacmp_y_load(6 - 1 downto 0);
    trunc_ln13_fu_364_p1 <= select_ln12_fu_237_p3(6 - 1 downto 0);
    trunc_ln28_1_fu_485_p4 <= sub_ln28_1_fu_479_p2(16 downto 1);
    trunc_ln28_2_fu_495_p4 <= sub_ln28_fu_465_p2(16 downto 1);
    trunc_ln29_1_fu_548_p4 <= sub_ln29_1_fu_542_p2(16 downto 1);
    trunc_ln29_2_fu_558_p4 <= sub_ln29_fu_528_p2(16 downto 1);
    trunc_ln32_fu_269_p1 <= select_ln12_1_fu_261_p3(6 - 1 downto 0);
    zext_ln28_1_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_72_fu_423_p3),64));
    zext_ln28_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_71_fu_404_p3),64));
    zext_ln29_1_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_5_fu_353_p2),64));
    zext_ln29_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_4_fu_342_p2),64));
    zext_ln32_3_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln32_fu_327_p2),64));
    zext_ln32_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln12_fu_237_p3),12));
end behav;
