// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module pyramidal_hs_compute_derivatives (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img1_address0,
        img1_ce0,
        img1_q0,
        img1_address1,
        img1_ce1,
        img1_q1,
        img2_address0,
        img2_ce0,
        img2_q0,
        Ix64_address0,
        Ix64_ce0,
        Ix64_we0,
        Ix64_d0,
        Iy64_address0,
        Iy64_ce0,
        Iy64_we0,
        Iy64_d0,
        It64_address0,
        It64_ce0,
        It64_we0,
        It64_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] img1_address0;
output   img1_ce0;
input  [15:0] img1_q0;
output  [11:0] img1_address1;
output   img1_ce1;
input  [15:0] img1_q1;
output  [11:0] img2_address0;
output   img2_ce0;
input  [15:0] img2_q0;
output  [11:0] Ix64_address0;
output   Ix64_ce0;
output   Ix64_we0;
output  [15:0] Ix64_d0;
output  [11:0] Iy64_address0;
output   Iy64_ce0;
output   Iy64_we0;
output  [15:0] Iy64_d0;
output  [11:0] It64_address0;
output   It64_ce0;
output   It64_we0;
output  [15:0] It64_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln12_fu_209_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln12_reg_610;
wire    ap_block_pp0_stage0_11001;
reg   [11:0] It64_addr_reg_614;
reg   [11:0] Ix64_addr_reg_619;
reg   [11:0] Iy64_addr_reg_624;
reg   [11:0] img1_addr_5_reg_629;
reg   [11:0] img1_addr_6_reg_634;
reg   [11:0] img1_addr_7_reg_639;
wire   [0:0] or_ln19_2_fu_392_p2;
reg   [0:0] or_ln19_2_reg_649;
reg   [15:0] img2_load_reg_663;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [15:0] ap_phi_mux_storemerge_phi_fu_183_p4;
wire   [15:0] sub_ln32_fu_583_p2;
wire    ap_block_pp0_stage2_11001;
wire   [63:0] zext_ln32_3_fu_333_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln29_fu_348_p1;
wire   [63:0] zext_ln29_1_fu_359_p1;
wire   [63:0] zext_ln28_fu_412_p1;
wire   [63:0] zext_ln28_1_fu_431_p1;
reg   [6:0] x_fu_68;
wire   [6:0] add_ln13_fu_436_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_x_load;
reg   [6:0] y_fu_72;
wire   [6:0] select_ln12_1_fu_261_p3;
reg   [6:0] ap_sig_allocacmp_y_load;
reg   [12:0] indvar_flatten_fu_76;
wire   [12:0] add_ln12_fu_215_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten_load;
reg    img1_ce1_local;
reg   [11:0] img1_address1_local;
reg    img1_ce0_local;
reg   [11:0] img1_address0_local;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
reg    img2_ce0_local;
reg    Ix64_we0_local;
reg   [15:0] Ix64_d0_local;
reg    Ix64_ce0_local;
reg   [11:0] Ix64_address0_local;
wire   [15:0] select_ln28_fu_511_p3;
reg    Iy64_we0_local;
reg   [15:0] Iy64_d0_local;
reg    Iy64_ce0_local;
reg   [11:0] Iy64_address0_local;
wire   [15:0] select_ln29_fu_574_p3;
reg    It64_we0_local;
reg    It64_ce0_local;
wire   [0:0] icmp_ln13_fu_231_p2;
wire   [5:0] trunc_ln12_fu_227_p1;
wire   [6:0] add_ln29_3_fu_251_p2;
wire   [5:0] trunc_ln32_fu_269_p1;
wire   [5:0] add_ln29_fu_245_p2;
wire   [5:0] trunc_ln12_1_fu_257_p1;
wire   [5:0] select_ln29_2_fu_293_p3;
wire   [5:0] add_ln29_2_fu_309_p2;
wire   [6:0] select_ln12_fu_237_p3;
wire   [11:0] tmp_fu_273_p3;
wire   [11:0] zext_ln32_fu_323_p1;
wire   [11:0] add_ln32_fu_327_p2;
wire   [11:0] tmp_s_fu_301_p3;
wire   [11:0] add_ln29_4_fu_342_p2;
wire   [11:0] tmp_70_fu_315_p3;
wire   [11:0] add_ln29_5_fu_353_p2;
wire   [0:0] icmp_ln19_1_fu_287_p2;
wire   [0:0] icmp_ln19_3_fu_374_p2;
wire   [0:0] icmp_ln19_fu_281_p2;
wire   [0:0] icmp_ln19_2_fu_368_p2;
wire   [0:0] or_ln19_1_fu_386_p2;
wire   [0:0] or_ln19_fu_380_p2;
wire   [5:0] trunc_ln13_fu_364_p1;
wire   [5:0] add_ln28_fu_398_p2;
wire   [11:0] tmp_71_fu_404_p3;
wire   [5:0] add_ln28_1_fu_417_p2;
wire   [11:0] tmp_72_fu_423_p3;
wire  signed [16:0] sext_ln28_fu_457_p1;
wire  signed [16:0] sext_ln28_1_fu_461_p1;
wire   [16:0] sub_ln28_fu_465_p2;
wire   [16:0] sub_ln28_1_fu_479_p2;
wire   [15:0] trunc_ln28_1_fu_485_p4;
wire   [0:0] tmp_85_fu_471_p3;
wire   [15:0] sub_ln28_2_fu_505_p2;
wire   [15:0] trunc_ln28_2_fu_495_p4;
wire  signed [16:0] sext_ln29_fu_520_p1;
wire  signed [16:0] sext_ln29_1_fu_524_p1;
wire   [16:0] sub_ln29_fu_528_p2;
wire   [16:0] sub_ln29_1_fu_542_p2;
wire   [15:0] trunc_ln29_1_fu_548_p4;
wire   [0:0] tmp_86_fu_534_p3;
wire   [15:0] sub_ln29_2_fu_568_p2;
wire   [15:0] trunc_ln29_2_fu_558_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 x_fu_68 = 7'd0;
#0 y_fu_72 = 7'd0;
#0 indvar_flatten_fu_76 = 13'd0;
#0 ap_done_reg = 1'b0;
end

pyramidal_hs_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln12_fu_209_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_76 <= add_ln12_fu_215_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_76 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln12_fu_209_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_68 <= add_ln13_fu_436_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_68 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln12_fu_209_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_72 <= select_ln12_1_fu_261_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_72 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        It64_addr_reg_614 <= zext_ln32_3_fu_333_p1;
        Ix64_addr_reg_619 <= zext_ln32_3_fu_333_p1;
        Iy64_addr_reg_624 <= zext_ln32_3_fu_333_p1;
        icmp_ln12_reg_610 <= icmp_ln12_fu_209_p2;
        img1_addr_5_reg_629 <= zext_ln29_fu_348_p1;
        img1_addr_6_reg_634 <= zext_ln29_1_fu_359_p1;
        img1_addr_7_reg_639 <= zext_ln32_3_fu_333_p1;
        or_ln19_2_reg_649 <= or_ln19_2_fu_392_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img2_load_reg_663 <= img2_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        It64_ce0_local = 1'b1;
    end else begin
        It64_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        It64_we0_local = 1'b1;
    end else begin
        It64_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Ix64_address0_local = Ix64_addr_reg_619;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Ix64_address0_local = zext_ln32_3_fu_333_p1;
    end else begin
        Ix64_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        Ix64_ce0_local = 1'b1;
    end else begin
        Ix64_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Ix64_d0_local = select_ln28_fu_511_p3;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Ix64_d0_local = 16'd0;
    end else begin
        Ix64_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln12_fu_209_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln19_2_fu_392_p2 == 1'd1)) | ((icmp_ln12_reg_610 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln19_2_reg_649 == 1'd0)))) begin
        Ix64_we0_local = 1'b1;
    end else begin
        Ix64_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Iy64_address0_local = Iy64_addr_reg_624;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Iy64_address0_local = zext_ln32_3_fu_333_p1;
    end else begin
        Iy64_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        Iy64_ce0_local = 1'b1;
    end else begin
        Iy64_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Iy64_d0_local = select_ln29_fu_574_p3;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Iy64_d0_local = 16'd0;
    end else begin
        Iy64_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln12_fu_209_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln19_2_fu_392_p2 == 1'd1)) | ((icmp_ln12_reg_610 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln19_2_reg_649 == 1'd0)))) begin
        Iy64_we0_local = 1'b1;
    end else begin
        Iy64_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_209_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_reg_610 == 1'd0) & (or_ln19_2_reg_649 == 1'd0))) begin
        ap_phi_mux_storemerge_phi_fu_183_p4 = sub_ln32_fu_583_p2;
    end else begin
        ap_phi_mux_storemerge_phi_fu_183_p4 = 16'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_load = 7'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_load = 7'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_72;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        img1_address0_local = img1_addr_7_reg_639;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img1_address0_local = img1_addr_6_reg_634;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img1_address0_local = zext_ln28_1_fu_431_p1;
    end else begin
        img1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img1_address1_local = img1_addr_5_reg_629;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img1_address1_local = zext_ln28_fu_412_p1;
    end else begin
        img1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img1_ce0_local = 1'b1;
    end else begin
        img1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img1_ce1_local = 1'b1;
    end else begin
        img1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img2_ce0_local = 1'b1;
    end else begin
        img2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign It64_address0 = It64_addr_reg_614;

assign It64_ce0 = It64_ce0_local;

assign It64_d0 = ap_phi_mux_storemerge_phi_fu_183_p4;

assign It64_we0 = It64_we0_local;

assign Ix64_address0 = Ix64_address0_local;

assign Ix64_ce0 = Ix64_ce0_local;

assign Ix64_d0 = Ix64_d0_local;

assign Ix64_we0 = Ix64_we0_local;

assign Iy64_address0 = Iy64_address0_local;

assign Iy64_ce0 = Iy64_ce0_local;

assign Iy64_d0 = Iy64_d0_local;

assign Iy64_we0 = Iy64_we0_local;

assign add_ln12_fu_215_p2 = (ap_sig_allocacmp_indvar_flatten_load + 13'd1);

assign add_ln13_fu_436_p2 = (select_ln12_fu_237_p3 + 7'd1);

assign add_ln28_1_fu_417_p2 = ($signed(trunc_ln13_fu_364_p1) + $signed(6'd63));

assign add_ln28_fu_398_p2 = (trunc_ln13_fu_364_p1 + 6'd1);

assign add_ln29_2_fu_309_p2 = ($signed(trunc_ln32_fu_269_p1) + $signed(6'd63));

assign add_ln29_3_fu_251_p2 = (ap_sig_allocacmp_y_load + 7'd1);

assign add_ln29_4_fu_342_p2 = (tmp_s_fu_301_p3 + zext_ln32_fu_323_p1);

assign add_ln29_5_fu_353_p2 = (tmp_70_fu_315_p3 + zext_ln32_fu_323_p1);

assign add_ln29_fu_245_p2 = (trunc_ln12_fu_227_p1 + 6'd2);

assign add_ln32_fu_327_p2 = (tmp_fu_273_p3 + zext_ln32_fu_323_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln12_fu_209_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_231_p2 = ((ap_sig_allocacmp_x_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln19_1_fu_287_p2 = ((select_ln12_1_fu_261_p3 == 7'd63) ? 1'b1 : 1'b0);

assign icmp_ln19_2_fu_368_p2 = ((select_ln12_fu_237_p3 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_3_fu_374_p2 = ((select_ln12_fu_237_p3 == 7'd63) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_281_p2 = ((select_ln12_1_fu_261_p3 == 7'd0) ? 1'b1 : 1'b0);

assign img1_address0 = img1_address0_local;

assign img1_address1 = img1_address1_local;

assign img1_ce0 = img1_ce0_local;

assign img1_ce1 = img1_ce1_local;

assign img2_address0 = zext_ln32_3_fu_333_p1;

assign img2_ce0 = img2_ce0_local;

assign or_ln19_1_fu_386_p2 = (icmp_ln19_fu_281_p2 | icmp_ln19_2_fu_368_p2);

assign or_ln19_2_fu_392_p2 = (or_ln19_fu_380_p2 | or_ln19_1_fu_386_p2);

assign or_ln19_fu_380_p2 = (icmp_ln19_3_fu_374_p2 | icmp_ln19_1_fu_287_p2);

assign select_ln12_1_fu_261_p3 = ((icmp_ln13_fu_231_p2[0:0] == 1'b1) ? add_ln29_3_fu_251_p2 : ap_sig_allocacmp_y_load);

assign select_ln12_fu_237_p3 = ((icmp_ln13_fu_231_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_x_load);

assign select_ln28_fu_511_p3 = ((tmp_85_fu_471_p3[0:0] == 1'b1) ? sub_ln28_2_fu_505_p2 : trunc_ln28_2_fu_495_p4);

assign select_ln29_2_fu_293_p3 = ((icmp_ln13_fu_231_p2[0:0] == 1'b1) ? add_ln29_fu_245_p2 : trunc_ln12_1_fu_257_p1);

assign select_ln29_fu_574_p3 = ((tmp_86_fu_534_p3[0:0] == 1'b1) ? sub_ln29_2_fu_568_p2 : trunc_ln29_2_fu_558_p4);

assign sext_ln28_1_fu_461_p1 = $signed(img1_q0);

assign sext_ln28_fu_457_p1 = $signed(img1_q1);

assign sext_ln29_1_fu_524_p1 = $signed(img1_q0);

assign sext_ln29_fu_520_p1 = $signed(img1_q1);

assign sub_ln28_1_fu_479_p2 = (17'd0 - sub_ln28_fu_465_p2);

assign sub_ln28_2_fu_505_p2 = (16'd0 - trunc_ln28_1_fu_485_p4);

assign sub_ln28_fu_465_p2 = ($signed(sext_ln28_fu_457_p1) - $signed(sext_ln28_1_fu_461_p1));

assign sub_ln29_1_fu_542_p2 = (17'd0 - sub_ln29_fu_528_p2);

assign sub_ln29_2_fu_568_p2 = (16'd0 - trunc_ln29_1_fu_548_p4);

assign sub_ln29_fu_528_p2 = ($signed(sext_ln29_fu_520_p1) - $signed(sext_ln29_1_fu_524_p1));

assign sub_ln32_fu_583_p2 = (img2_load_reg_663 - img1_q0);

assign tmp_70_fu_315_p3 = {{add_ln29_2_fu_309_p2}, {6'd0}};

assign tmp_71_fu_404_p3 = {{trunc_ln32_fu_269_p1}, {add_ln28_fu_398_p2}};

assign tmp_72_fu_423_p3 = {{trunc_ln32_fu_269_p1}, {add_ln28_1_fu_417_p2}};

assign tmp_85_fu_471_p3 = sub_ln28_fu_465_p2[32'd16];

assign tmp_86_fu_534_p3 = sub_ln29_fu_528_p2[32'd16];

assign tmp_fu_273_p3 = {{trunc_ln32_fu_269_p1}, {6'd0}};

assign tmp_s_fu_301_p3 = {{select_ln29_2_fu_293_p3}, {6'd0}};

assign trunc_ln12_1_fu_257_p1 = add_ln29_3_fu_251_p2[5:0];

assign trunc_ln12_fu_227_p1 = ap_sig_allocacmp_y_load[5:0];

assign trunc_ln13_fu_364_p1 = select_ln12_fu_237_p3[5:0];

assign trunc_ln28_1_fu_485_p4 = {{sub_ln28_1_fu_479_p2[16:1]}};

assign trunc_ln28_2_fu_495_p4 = {{sub_ln28_fu_465_p2[16:1]}};

assign trunc_ln29_1_fu_548_p4 = {{sub_ln29_1_fu_542_p2[16:1]}};

assign trunc_ln29_2_fu_558_p4 = {{sub_ln29_fu_528_p2[16:1]}};

assign trunc_ln32_fu_269_p1 = select_ln12_1_fu_261_p3[5:0];

assign zext_ln28_1_fu_431_p1 = tmp_72_fu_423_p3;

assign zext_ln28_fu_412_p1 = tmp_71_fu_404_p3;

assign zext_ln29_1_fu_359_p1 = add_ln29_5_fu_353_p2;

assign zext_ln29_fu_348_p1 = add_ln29_4_fu_342_p2;

assign zext_ln32_3_fu_333_p1 = add_ln32_fu_327_p2;

assign zext_ln32_fu_323_p1 = select_ln12_fu_237_p3;

endmodule //pyramidal_hs_compute_derivatives
