// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module pyramidal_hs_compute_derivatives_16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Ix16_address0,
        Ix16_ce0,
        Ix16_we0,
        Ix16_d0,
        Ix16_address1,
        Ix16_ce1,
        Ix16_we1,
        Ix16_d1,
        Iy16_address0,
        Iy16_ce0,
        Iy16_we0,
        Iy16_d0,
        Iy16_address1,
        Iy16_ce1,
        Iy16_we1,
        Iy16_d1,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_q0,
        img2_16_address0,
        img2_16_ce0,
        img2_16_q0,
        It16_address0,
        It16_ce0,
        It16_we0,
        It16_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] Ix16_address0;
output   Ix16_ce0;
output   Ix16_we0;
output  [15:0] Ix16_d0;
output  [7:0] Ix16_address1;
output   Ix16_ce1;
output   Ix16_we1;
output  [15:0] Ix16_d1;
output  [7:0] Iy16_address0;
output   Iy16_ce0;
output   Iy16_we0;
output  [15:0] Iy16_d0;
output  [7:0] Iy16_address1;
output   Iy16_ce1;
output   Iy16_we1;
output  [15:0] Iy16_d1;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_q0;
output  [7:0] img2_16_address0;
output   img2_16_ce0;
input  [15:0] img2_16_q0;
output  [7:0] It16_address0;
output   It16_ce0;
output   It16_we0;
output  [15:0] It16_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln70_fu_705_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln70_reg_1575;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter1_reg;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter2_reg;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter3_reg;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter4_reg;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter5_reg;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter6_reg;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter7_reg;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter8_reg;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter9_reg;
reg   [0:0] icmp_ln70_reg_1575_pp0_iter10_reg;
wire   [4:0] select_ln70_fu_729_p3;
reg   [4:0] select_ln70_reg_1579;
wire   [4:0] select_ln70_1_fu_749_p3;
reg   [4:0] select_ln70_1_reg_1586;
reg   [4:0] select_ln70_1_reg_1586_pp0_iter1_reg;
reg   [4:0] select_ln70_1_reg_1586_pp0_iter2_reg;
reg   [4:0] select_ln70_1_reg_1586_pp0_iter3_reg;
reg   [4:0] select_ln70_1_reg_1586_pp0_iter4_reg;
reg   [4:0] select_ln70_1_reg_1586_pp0_iter5_reg;
reg   [4:0] select_ln70_1_reg_1586_pp0_iter6_reg;
reg   [4:0] select_ln70_1_reg_1586_pp0_iter7_reg;
reg   [4:0] select_ln70_1_reg_1586_pp0_iter8_reg;
wire   [4:0] select_ln70_2_fu_757_p3;
reg   [4:0] select_ln70_2_reg_1591;
reg   [4:0] select_ln70_2_reg_1591_pp0_iter1_reg;
reg   [4:0] select_ln70_2_reg_1591_pp0_iter2_reg;
reg   [4:0] select_ln70_2_reg_1591_pp0_iter3_reg;
reg   [4:0] select_ln70_2_reg_1591_pp0_iter4_reg;
reg   [4:0] select_ln70_2_reg_1591_pp0_iter5_reg;
reg   [4:0] select_ln70_2_reg_1591_pp0_iter6_reg;
reg   [4:0] select_ln70_2_reg_1591_pp0_iter7_reg;
reg   [4:0] select_ln70_2_reg_1591_pp0_iter8_reg;
wire   [3:0] trunc_ln80_fu_765_p1;
reg   [3:0] trunc_ln80_reg_1598;
wire   [3:0] trunc_ln71_fu_787_p1;
reg   [3:0] trunc_ln71_reg_1603;
reg   [3:0] trunc_ln71_reg_1603_pp0_iter1_reg;
reg   [3:0] trunc_ln71_reg_1603_pp0_iter2_reg;
reg   [3:0] trunc_ln71_reg_1603_pp0_iter3_reg;
reg   [3:0] trunc_ln71_reg_1603_pp0_iter4_reg;
reg   [3:0] trunc_ln71_reg_1603_pp0_iter5_reg;
reg   [3:0] trunc_ln71_reg_1603_pp0_iter6_reg;
reg   [3:0] trunc_ln71_reg_1603_pp0_iter7_reg;
reg   [3:0] trunc_ln71_reg_1603_pp0_iter8_reg;
wire   [0:0] or_ln73_2_fu_821_p2;
reg   [0:0] or_ln73_2_reg_1609;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter1_reg;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter2_reg;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter3_reg;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter4_reg;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter5_reg;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter6_reg;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter7_reg;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter8_reg;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter9_reg;
reg   [0:0] or_ln73_2_reg_1609_pp0_iter10_reg;
reg   [7:0] It16_addr_reg_1613;
reg   [7:0] It16_addr_reg_1613_pp0_iter2_reg;
reg   [7:0] It16_addr_reg_1613_pp0_iter3_reg;
reg   [7:0] It16_addr_reg_1613_pp0_iter4_reg;
reg   [7:0] It16_addr_reg_1613_pp0_iter5_reg;
reg   [7:0] It16_addr_reg_1613_pp0_iter6_reg;
reg   [7:0] It16_addr_reg_1613_pp0_iter7_reg;
reg   [7:0] It16_addr_reg_1613_pp0_iter8_reg;
reg   [7:0] It16_addr_reg_1613_pp0_iter9_reg;
reg   [7:0] It16_addr_reg_1613_pp0_iter10_reg;
reg   [7:0] Ix16_addr_reg_1618;
reg   [7:0] Ix16_addr_reg_1618_pp0_iter2_reg;
reg   [7:0] Ix16_addr_reg_1618_pp0_iter3_reg;
reg   [7:0] Ix16_addr_reg_1618_pp0_iter4_reg;
reg   [7:0] Ix16_addr_reg_1618_pp0_iter5_reg;
reg   [7:0] Ix16_addr_reg_1618_pp0_iter6_reg;
reg   [7:0] Ix16_addr_reg_1618_pp0_iter7_reg;
reg   [7:0] Ix16_addr_reg_1618_pp0_iter8_reg;
reg   [7:0] Ix16_addr_reg_1618_pp0_iter9_reg;
reg   [7:0] Ix16_addr_reg_1618_pp0_iter10_reg;
reg   [7:0] Iy16_addr_reg_1623;
reg   [7:0] Iy16_addr_reg_1623_pp0_iter2_reg;
reg   [7:0] Iy16_addr_reg_1623_pp0_iter3_reg;
reg   [7:0] Iy16_addr_reg_1623_pp0_iter4_reg;
reg   [7:0] Iy16_addr_reg_1623_pp0_iter5_reg;
reg   [7:0] Iy16_addr_reg_1623_pp0_iter6_reg;
reg   [7:0] Iy16_addr_reg_1623_pp0_iter7_reg;
reg   [7:0] Iy16_addr_reg_1623_pp0_iter8_reg;
reg   [7:0] Iy16_addr_reg_1623_pp0_iter9_reg;
reg   [7:0] Iy16_addr_reg_1623_pp0_iter10_reg;
reg   [7:0] img2_16_addr_reg_1628;
reg   [7:0] img2_16_addr_reg_1628_pp0_iter2_reg;
reg   [7:0] img2_16_addr_reg_1628_pp0_iter3_reg;
reg   [7:0] img2_16_addr_reg_1628_pp0_iter4_reg;
reg   [7:0] img2_16_addr_reg_1628_pp0_iter5_reg;
reg   [7:0] img2_16_addr_reg_1628_pp0_iter6_reg;
reg   [7:0] img2_16_addr_reg_1628_pp0_iter7_reg;
reg   [7:0] img2_16_addr_reg_1628_pp0_iter8_reg;
reg   [3:0] tmp_80_reg_1633;
reg   [3:0] tmp_80_reg_1633_pp0_iter2_reg;
reg   [3:0] tmp_80_reg_1633_pp0_iter3_reg;
reg   [3:0] tmp_80_reg_1633_pp0_iter4_reg;
reg   [3:0] tmp_80_reg_1633_pp0_iter5_reg;
reg   [3:0] tmp_80_reg_1633_pp0_iter6_reg;
reg   [3:0] tmp_80_reg_1633_pp0_iter7_reg;
reg   [3:0] tmp_80_reg_1633_pp0_iter8_reg;
wire   [1:0] trunc_ln70_fu_905_p1;
reg   [1:0] trunc_ln70_reg_1643;
reg   [1:0] trunc_ln70_reg_1643_pp0_iter9_reg;
reg   [2:0] tmp_78_reg_1652;
reg   [4:0] tmp_79_reg_1657;
wire   [1:0] trunc_ln71_1_fu_929_p1;
reg   [1:0] trunc_ln71_1_reg_1662;
reg   [1:0] trunc_ln71_1_reg_1662_pp0_iter9_reg;
reg   [0:0] tmp_83_reg_1900;
reg   [15:0] trunc_ln78_1_reg_1905;
reg   [15:0] trunc_ln78_2_reg_1910;
reg   [0:0] tmp_84_reg_1915;
reg   [15:0] trunc_ln79_1_reg_1920;
reg   [15:0] trunc_ln79_2_reg_1925;
wire   [15:0] sub_ln80_fu_1524_p2;
wire   [15:0] ap_phi_reg_pp0_iter0_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter1_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter2_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter3_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter4_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter5_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter6_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter7_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter8_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter9_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter10_storemerge_reg_613;
reg   [15:0] ap_phi_reg_pp0_iter11_storemerge_reg_613;
wire   [63:0] zext_ln80_1_fu_864_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln79_3_fu_1072_p1;
wire   [63:0] zext_ln79_4_fu_1091_p1;
wire   [63:0] zext_ln80_2_fu_1110_p1;
wire   [63:0] zext_ln78_3_fu_1158_p1;
wire   [63:0] zext_ln78_6_fu_1206_p1;
reg   [4:0] x_fu_136;
wire   [4:0] add_ln71_fu_827_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_x_load;
reg   [4:0] y_fu_140;
reg   [4:0] ap_sig_allocacmp_y_load;
reg   [8:0] indvar_flatten_fu_144;
wire   [8:0] add_ln70_fu_711_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
reg    Ix16_we1_local;
reg    Ix16_ce1_local;
reg    Ix16_we0_local;
wire   [15:0] select_ln78_fu_1535_p3;
reg    Ix16_ce0_local;
reg    Iy16_we1_local;
reg    Iy16_ce1_local;
reg    Iy16_we0_local;
wire   [15:0] select_ln79_fu_1547_p3;
reg    Iy16_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_ce0_local;
reg   [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_ce0_local;
reg   [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_ce0_local;
reg   [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_ce0_local;
reg   [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_ce0_local;
reg   [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_ce0_local;
reg   [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_ce0_local;
reg   [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_ce0_local;
reg   [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_ce0_local;
reg   [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0_local;
reg    img2_16_ce0_local;
reg    It16_we0_local;
reg    It16_ce0_local;
wire   [63:0] grp_fu_625_p0;
wire   [65:0] grp_fu_625_p1;
wire   [15:0] grp_fu_630_p7;
wire   [15:0] grp_fu_649_p7;
wire   [15:0] grp_fu_668_p7;
wire   [0:0] icmp_ln71_fu_723_p2;
wire   [4:0] add_ln79_fu_737_p2;
wire   [4:0] add_ln79_2_fu_743_p2;
wire   [2:0] grp_fu_769_p1;
wire   [2:0] grp_fu_791_p1;
wire   [0:0] icmp_ln73_1_fu_781_p2;
wire   [0:0] icmp_ln73_3_fu_803_p2;
wire   [0:0] icmp_ln73_fu_775_p2;
wire   [0:0] icmp_ln73_2_fu_797_p2;
wire   [0:0] or_ln73_1_fu_815_p2;
wire   [0:0] or_ln73_fu_809_p2;
wire   [7:0] tmp_69_fu_848_p3;
wire   [7:0] zext_ln80_fu_855_p1;
wire   [7:0] add_ln80_fu_858_p2;
wire   [4:0] mul_ln71_1_fu_875_p0;
wire   [6:0] mul_ln71_1_fu_875_p1;
wire   [10:0] mul_ln71_1_fu_875_p2;
wire   [4:0] add_ln79_1_fu_891_p2;
wire  signed [63:0] sext_ln71_fu_896_p1;
wire   [1:0] grp_fu_769_p2;
wire   [128:0] grp_fu_625_p2;
wire   [1:0] grp_fu_791_p2;
wire   [4:0] mul_ln70_fu_936_p0;
wire   [6:0] mul_ln70_fu_936_p1;
wire   [10:0] mul_ln70_fu_936_p2;
wire   [3:0] tmp_70_fu_942_p4;
wire   [2:0] tmp_71_fu_952_p4;
wire   [4:0] tmp_72_fu_962_p3;
wire   [5:0] tmp_73_fu_970_p3;
wire   [5:0] zext_ln78_fu_978_p1;
wire   [4:0] mul_ln79_fu_991_p0;
wire   [6:0] mul_ln79_fu_991_p1;
wire   [10:0] mul_ln79_fu_991_p2;
wire   [3:0] tmp_74_fu_997_p4;
wire   [2:0] tmp_75_fu_1007_p4;
wire   [4:0] tmp_76_fu_1017_p3;
wire   [5:0] tmp_77_fu_1025_p3;
wire   [5:0] zext_ln79_1_fu_1033_p1;
wire   [5:0] p_shl_fu_1043_p3;
wire   [5:0] p_shl1_fu_1050_p3;
wire   [5:0] sub_ln79_3_fu_1037_p2;
wire   [5:0] zext_ln79_2_fu_1063_p1;
wire   [5:0] add_ln79_3_fu_1066_p2;
wire   [5:0] sub_ln79_4_fu_1057_p2;
wire   [5:0] add_ln79_4_fu_1085_p2;
wire   [5:0] sub_ln70_fu_982_p2;
wire   [5:0] add_ln80_1_fu_1104_p2;
wire   [3:0] add_ln78_fu_1123_p2;
wire   [3:0] mul_ln78_fu_1132_p0;
wire   [5:0] mul_ln78_fu_1132_p1;
wire   [8:0] mul_ln78_fu_1132_p2;
wire   [2:0] tmp_81_fu_1138_p4;
wire   [5:0] zext_ln78_2_fu_1148_p1;
wire   [5:0] add_ln78_2_fu_1152_p2;
wire   [3:0] add_ln78_1_fu_1171_p2;
wire   [3:0] mul_ln78_1_fu_1180_p0;
wire   [5:0] mul_ln78_1_fu_1180_p1;
wire   [8:0] mul_ln78_1_fu_1180_p2;
wire   [2:0] tmp_82_fu_1186_p4;
wire   [5:0] zext_ln78_5_fu_1196_p1;
wire   [5:0] add_ln78_3_fu_1200_p2;
wire   [15:0] tmp_fu_1219_p7;
wire   [15:0] tmp_s_fu_1238_p7;
wire   [15:0] tmp_51_fu_1257_p7;
wire   [15:0] tmp_fu_1219_p9;
wire   [15:0] tmp_s_fu_1238_p9;
wire   [15:0] tmp_51_fu_1257_p9;
wire   [15:0] tmp_52_fu_1276_p7;
wire   [15:0] tmp_52_fu_1276_p9;
wire   [15:0] tmp_53_fu_1299_p7;
wire   [15:0] tmp_54_fu_1318_p7;
wire   [15:0] tmp_55_fu_1337_p7;
wire   [15:0] tmp_53_fu_1299_p9;
wire   [15:0] tmp_54_fu_1318_p9;
wire   [15:0] tmp_55_fu_1337_p9;
wire   [15:0] tmp_56_fu_1356_p7;
wire   [15:0] tmp_56_fu_1356_p9;
wire  signed [16:0] sext_ln78_fu_1295_p1;
wire  signed [16:0] sext_ln78_1_fu_1375_p1;
wire   [16:0] sub_ln78_fu_1379_p2;
wire   [16:0] sub_ln78_1_fu_1393_p2;
wire   [15:0] grp_fu_630_p9;
wire   [15:0] grp_fu_649_p9;
wire   [15:0] grp_fu_668_p9;
wire   [15:0] tmp_60_fu_1419_p7;
wire   [15:0] tmp_60_fu_1419_p9;
wire   [15:0] tmp_64_fu_1442_p7;
wire   [15:0] tmp_64_fu_1442_p9;
wire  signed [16:0] sext_ln79_fu_1438_p1;
wire  signed [16:0] sext_ln79_1_fu_1461_p1;
wire   [16:0] sub_ln79_fu_1465_p2;
wire   [16:0] sub_ln79_1_fu_1479_p2;
wire   [15:0] tmp_68_fu_1505_p7;
wire   [15:0] tmp_68_fu_1505_p9;
wire   [15:0] sub_ln78_2_fu_1530_p2;
wire   [15:0] sub_ln79_2_fu_1542_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [128:0] grp_fu_625_p00;
wire   [10:0] mul_ln70_fu_936_p00;
wire   [10:0] mul_ln71_1_fu_875_p00;
wire   [8:0] mul_ln78_1_fu_1180_p00;
wire   [8:0] mul_ln78_fu_1132_p00;
wire   [10:0] mul_ln79_fu_991_p00;
reg    ap_condition_426;
reg    ap_condition_1295;
wire   [1:0] grp_fu_630_p1;
wire   [1:0] grp_fu_630_p3;
wire  signed [1:0] grp_fu_630_p5;
wire   [1:0] grp_fu_649_p1;
wire   [1:0] grp_fu_649_p3;
wire  signed [1:0] grp_fu_649_p5;
wire   [1:0] grp_fu_668_p1;
wire   [1:0] grp_fu_668_p3;
wire  signed [1:0] grp_fu_668_p5;
wire  signed [1:0] tmp_fu_1219_p1;
wire   [1:0] tmp_fu_1219_p3;
wire   [1:0] tmp_fu_1219_p5;
wire  signed [1:0] tmp_s_fu_1238_p1;
wire   [1:0] tmp_s_fu_1238_p3;
wire   [1:0] tmp_s_fu_1238_p5;
wire  signed [1:0] tmp_51_fu_1257_p1;
wire   [1:0] tmp_51_fu_1257_p3;
wire   [1:0] tmp_51_fu_1257_p5;
wire   [1:0] tmp_52_fu_1276_p1;
wire   [1:0] tmp_52_fu_1276_p3;
wire  signed [1:0] tmp_52_fu_1276_p5;
wire   [1:0] tmp_53_fu_1299_p1;
wire  signed [1:0] tmp_53_fu_1299_p3;
wire   [1:0] tmp_53_fu_1299_p5;
wire   [1:0] tmp_54_fu_1318_p1;
wire  signed [1:0] tmp_54_fu_1318_p3;
wire   [1:0] tmp_54_fu_1318_p5;
wire   [1:0] tmp_55_fu_1337_p1;
wire  signed [1:0] tmp_55_fu_1337_p3;
wire   [1:0] tmp_55_fu_1337_p5;
wire   [1:0] tmp_56_fu_1356_p1;
wire   [1:0] tmp_56_fu_1356_p3;
wire  signed [1:0] tmp_56_fu_1356_p5;
wire  signed [1:0] tmp_60_fu_1419_p1;
wire   [1:0] tmp_60_fu_1419_p3;
wire   [1:0] tmp_60_fu_1419_p5;
wire   [1:0] tmp_64_fu_1442_p1;
wire  signed [1:0] tmp_64_fu_1442_p3;
wire   [1:0] tmp_64_fu_1442_p5;
wire   [1:0] tmp_68_fu_1505_p1;
wire   [1:0] tmp_68_fu_1505_p3;
wire  signed [1:0] tmp_68_fu_1505_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 x_fu_136 = 5'd0;
#0 y_fu_140 = 5'd0;
#0 indvar_flatten_fu_144 = 9'd0;
#0 ap_done_reg = 1'b0;
end

pyramidal_hs_mul_64ns_66ns_129_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 66 ),
    .dout_WIDTH( 129 ))
mul_64ns_66ns_129_5_1_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_625_p0),
    .din1(grp_fu_625_p1),
    .ce(1'b1),
    .dout(grp_fu_625_p2)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U69(
    .din0(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_q0),
    .din1(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_q0),
    .din2(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_q0),
    .def(grp_fu_630_p7),
    .sel(trunc_ln71_1_reg_1662_pp0_iter9_reg),
    .dout(grp_fu_630_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U70(
    .din0(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_q0),
    .din1(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_q0),
    .din2(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_q0),
    .def(grp_fu_649_p7),
    .sel(trunc_ln71_1_reg_1662_pp0_iter9_reg),
    .dout(grp_fu_649_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U71(
    .din0(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_q0),
    .din1(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_q0),
    .din2(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_q0),
    .def(grp_fu_668_p7),
    .sel(trunc_ln71_1_reg_1662_pp0_iter9_reg),
    .dout(grp_fu_668_p9)
);

pyramidal_hs_urem_5ns_3ns_2_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_5ns_3ns_2_9_1_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln70_2_fu_757_p3),
    .din1(grp_fu_769_p1),
    .ce(1'b1),
    .dout(grp_fu_769_p2)
);

pyramidal_hs_urem_5ns_3ns_2_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_5ns_3ns_2_9_1_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln70_fu_729_p3),
    .din1(grp_fu_791_p1),
    .ce(1'b1),
    .dout(grp_fu_791_p2)
);

pyramidal_hs_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U74(
    .din0(mul_ln71_1_fu_875_p0),
    .din1(mul_ln71_1_fu_875_p1),
    .dout(mul_ln71_1_fu_875_p2)
);

pyramidal_hs_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U75(
    .din0(mul_ln70_fu_936_p0),
    .din1(mul_ln70_fu_936_p1),
    .dout(mul_ln70_fu_936_p2)
);

pyramidal_hs_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U76(
    .din0(mul_ln79_fu_991_p0),
    .din1(mul_ln79_fu_991_p1),
    .dout(mul_ln79_fu_991_p2)
);

pyramidal_hs_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U77(
    .din0(mul_ln78_fu_1132_p0),
    .din1(mul_ln78_fu_1132_p1),
    .dout(mul_ln78_fu_1132_p2)
);

pyramidal_hs_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U78(
    .din0(mul_ln78_1_fu_1180_p0),
    .din1(mul_ln78_1_fu_1180_p1),
    .dout(mul_ln78_1_fu_1180_p2)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_x_U79(
    .din0(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_q0),
    .din1(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_q0),
    .din2(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_q0),
    .def(tmp_fu_1219_p7),
    .sel(trunc_ln71_1_reg_1662_pp0_iter9_reg),
    .dout(tmp_fu_1219_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_x_U80(
    .din0(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_q0),
    .din1(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_q0),
    .din2(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_q0),
    .def(tmp_s_fu_1238_p7),
    .sel(trunc_ln71_1_reg_1662_pp0_iter9_reg),
    .dout(tmp_s_fu_1238_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_x_U81(
    .din0(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_q0),
    .din1(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_q0),
    .din2(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_q0),
    .def(tmp_51_fu_1257_p7),
    .sel(trunc_ln71_1_reg_1662_pp0_iter9_reg),
    .dout(tmp_51_fu_1257_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U82(
    .din0(tmp_fu_1219_p9),
    .din1(tmp_s_fu_1238_p9),
    .din2(tmp_51_fu_1257_p9),
    .def(tmp_52_fu_1276_p7),
    .sel(trunc_ln70_reg_1643_pp0_iter9_reg),
    .dout(tmp_52_fu_1276_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U83(
    .din0(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_q0),
    .din1(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_q0),
    .din2(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_q0),
    .def(tmp_53_fu_1299_p7),
    .sel(trunc_ln71_1_reg_1662_pp0_iter9_reg),
    .dout(tmp_53_fu_1299_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U84(
    .din0(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_q0),
    .din1(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_q0),
    .din2(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_q0),
    .def(tmp_54_fu_1318_p7),
    .sel(trunc_ln71_1_reg_1662_pp0_iter9_reg),
    .dout(tmp_54_fu_1318_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U85(
    .din0(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_q0),
    .din1(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_q0),
    .din2(p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_q0),
    .def(tmp_55_fu_1337_p7),
    .sel(trunc_ln71_1_reg_1662_pp0_iter9_reg),
    .dout(tmp_55_fu_1337_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U86(
    .din0(tmp_53_fu_1299_p9),
    .din1(tmp_54_fu_1318_p9),
    .din2(tmp_55_fu_1337_p9),
    .def(tmp_56_fu_1356_p7),
    .sel(trunc_ln70_reg_1643_pp0_iter9_reg),
    .dout(tmp_56_fu_1356_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_x_U87(
    .din0(grp_fu_630_p9),
    .din1(grp_fu_649_p9),
    .din2(grp_fu_668_p9),
    .def(tmp_60_fu_1419_p7),
    .sel(trunc_ln70_reg_1643_pp0_iter9_reg),
    .dout(tmp_60_fu_1419_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U88(
    .din0(grp_fu_630_p9),
    .din1(grp_fu_649_p9),
    .din2(grp_fu_668_p9),
    .def(tmp_64_fu_1442_p7),
    .sel(trunc_ln70_reg_1643_pp0_iter9_reg),
    .dout(tmp_64_fu_1442_p9)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U89(
    .din0(grp_fu_630_p9),
    .din1(grp_fu_649_p9),
    .din2(grp_fu_668_p9),
    .def(tmp_68_fu_1505_p7),
    .sel(trunc_ln70_reg_1643_pp0_iter9_reg),
    .dout(tmp_68_fu_1505_p9)
);

pyramidal_hs_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((or_ln73_2_reg_1609_pp0_iter9_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter9_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter11_storemerge_reg_613 <= sub_ln80_fu_1524_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter11_storemerge_reg_613 <= ap_phi_reg_pp0_iter10_storemerge_reg_613;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_426)) begin
        if (((or_ln73_2_reg_1609 == 1'd1) & (icmp_ln70_reg_1575 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_storemerge_reg_613 <= 16'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_storemerge_reg_613 <= ap_phi_reg_pp0_iter1_storemerge_reg_613;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln70_fu_705_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_144 <= add_ln70_fu_711_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_144 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln70_fu_705_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_136 <= add_ln71_fu_827_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_136 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln70_fu_705_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_140 <= select_ln70_2_fu_757_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_140 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        It16_addr_reg_1613 <= zext_ln80_1_fu_864_p1;
        Ix16_addr_reg_1618 <= zext_ln80_1_fu_864_p1;
        Iy16_addr_reg_1623 <= zext_ln80_1_fu_864_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln70_reg_1575 <= icmp_ln70_fu_705_p2;
        icmp_ln70_reg_1575_pp0_iter1_reg <= icmp_ln70_reg_1575;
        img2_16_addr_reg_1628 <= zext_ln80_1_fu_864_p1;
        or_ln73_2_reg_1609 <= or_ln73_2_fu_821_p2;
        or_ln73_2_reg_1609_pp0_iter1_reg <= or_ln73_2_reg_1609;
        select_ln70_1_reg_1586 <= select_ln70_1_fu_749_p3;
        select_ln70_1_reg_1586_pp0_iter1_reg <= select_ln70_1_reg_1586;
        select_ln70_2_reg_1591 <= select_ln70_2_fu_757_p3;
        select_ln70_2_reg_1591_pp0_iter1_reg <= select_ln70_2_reg_1591;
        select_ln70_reg_1579 <= select_ln70_fu_729_p3;
        tmp_80_reg_1633 <= {{mul_ln71_1_fu_875_p2[10:7]}};
        trunc_ln71_reg_1603 <= trunc_ln71_fu_787_p1;
        trunc_ln71_reg_1603_pp0_iter1_reg <= trunc_ln71_reg_1603;
        trunc_ln80_reg_1598 <= trunc_ln80_fu_765_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        It16_addr_reg_1613_pp0_iter10_reg <= It16_addr_reg_1613_pp0_iter9_reg;
        It16_addr_reg_1613_pp0_iter2_reg <= It16_addr_reg_1613;
        It16_addr_reg_1613_pp0_iter3_reg <= It16_addr_reg_1613_pp0_iter2_reg;
        It16_addr_reg_1613_pp0_iter4_reg <= It16_addr_reg_1613_pp0_iter3_reg;
        It16_addr_reg_1613_pp0_iter5_reg <= It16_addr_reg_1613_pp0_iter4_reg;
        It16_addr_reg_1613_pp0_iter6_reg <= It16_addr_reg_1613_pp0_iter5_reg;
        It16_addr_reg_1613_pp0_iter7_reg <= It16_addr_reg_1613_pp0_iter6_reg;
        It16_addr_reg_1613_pp0_iter8_reg <= It16_addr_reg_1613_pp0_iter7_reg;
        It16_addr_reg_1613_pp0_iter9_reg <= It16_addr_reg_1613_pp0_iter8_reg;
        Ix16_addr_reg_1618_pp0_iter10_reg <= Ix16_addr_reg_1618_pp0_iter9_reg;
        Ix16_addr_reg_1618_pp0_iter2_reg <= Ix16_addr_reg_1618;
        Ix16_addr_reg_1618_pp0_iter3_reg <= Ix16_addr_reg_1618_pp0_iter2_reg;
        Ix16_addr_reg_1618_pp0_iter4_reg <= Ix16_addr_reg_1618_pp0_iter3_reg;
        Ix16_addr_reg_1618_pp0_iter5_reg <= Ix16_addr_reg_1618_pp0_iter4_reg;
        Ix16_addr_reg_1618_pp0_iter6_reg <= Ix16_addr_reg_1618_pp0_iter5_reg;
        Ix16_addr_reg_1618_pp0_iter7_reg <= Ix16_addr_reg_1618_pp0_iter6_reg;
        Ix16_addr_reg_1618_pp0_iter8_reg <= Ix16_addr_reg_1618_pp0_iter7_reg;
        Ix16_addr_reg_1618_pp0_iter9_reg <= Ix16_addr_reg_1618_pp0_iter8_reg;
        Iy16_addr_reg_1623_pp0_iter10_reg <= Iy16_addr_reg_1623_pp0_iter9_reg;
        Iy16_addr_reg_1623_pp0_iter2_reg <= Iy16_addr_reg_1623;
        Iy16_addr_reg_1623_pp0_iter3_reg <= Iy16_addr_reg_1623_pp0_iter2_reg;
        Iy16_addr_reg_1623_pp0_iter4_reg <= Iy16_addr_reg_1623_pp0_iter3_reg;
        Iy16_addr_reg_1623_pp0_iter5_reg <= Iy16_addr_reg_1623_pp0_iter4_reg;
        Iy16_addr_reg_1623_pp0_iter6_reg <= Iy16_addr_reg_1623_pp0_iter5_reg;
        Iy16_addr_reg_1623_pp0_iter7_reg <= Iy16_addr_reg_1623_pp0_iter6_reg;
        Iy16_addr_reg_1623_pp0_iter8_reg <= Iy16_addr_reg_1623_pp0_iter7_reg;
        Iy16_addr_reg_1623_pp0_iter9_reg <= Iy16_addr_reg_1623_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln70_reg_1575_pp0_iter10_reg <= icmp_ln70_reg_1575_pp0_iter9_reg;
        icmp_ln70_reg_1575_pp0_iter2_reg <= icmp_ln70_reg_1575_pp0_iter1_reg;
        icmp_ln70_reg_1575_pp0_iter3_reg <= icmp_ln70_reg_1575_pp0_iter2_reg;
        icmp_ln70_reg_1575_pp0_iter4_reg <= icmp_ln70_reg_1575_pp0_iter3_reg;
        icmp_ln70_reg_1575_pp0_iter5_reg <= icmp_ln70_reg_1575_pp0_iter4_reg;
        icmp_ln70_reg_1575_pp0_iter6_reg <= icmp_ln70_reg_1575_pp0_iter5_reg;
        icmp_ln70_reg_1575_pp0_iter7_reg <= icmp_ln70_reg_1575_pp0_iter6_reg;
        icmp_ln70_reg_1575_pp0_iter8_reg <= icmp_ln70_reg_1575_pp0_iter7_reg;
        icmp_ln70_reg_1575_pp0_iter9_reg <= icmp_ln70_reg_1575_pp0_iter8_reg;
        img2_16_addr_reg_1628_pp0_iter2_reg <= img2_16_addr_reg_1628;
        img2_16_addr_reg_1628_pp0_iter3_reg <= img2_16_addr_reg_1628_pp0_iter2_reg;
        img2_16_addr_reg_1628_pp0_iter4_reg <= img2_16_addr_reg_1628_pp0_iter3_reg;
        img2_16_addr_reg_1628_pp0_iter5_reg <= img2_16_addr_reg_1628_pp0_iter4_reg;
        img2_16_addr_reg_1628_pp0_iter6_reg <= img2_16_addr_reg_1628_pp0_iter5_reg;
        img2_16_addr_reg_1628_pp0_iter7_reg <= img2_16_addr_reg_1628_pp0_iter6_reg;
        img2_16_addr_reg_1628_pp0_iter8_reg <= img2_16_addr_reg_1628_pp0_iter7_reg;
        or_ln73_2_reg_1609_pp0_iter10_reg <= or_ln73_2_reg_1609_pp0_iter9_reg;
        or_ln73_2_reg_1609_pp0_iter2_reg <= or_ln73_2_reg_1609_pp0_iter1_reg;
        or_ln73_2_reg_1609_pp0_iter3_reg <= or_ln73_2_reg_1609_pp0_iter2_reg;
        or_ln73_2_reg_1609_pp0_iter4_reg <= or_ln73_2_reg_1609_pp0_iter3_reg;
        or_ln73_2_reg_1609_pp0_iter5_reg <= or_ln73_2_reg_1609_pp0_iter4_reg;
        or_ln73_2_reg_1609_pp0_iter6_reg <= or_ln73_2_reg_1609_pp0_iter5_reg;
        or_ln73_2_reg_1609_pp0_iter7_reg <= or_ln73_2_reg_1609_pp0_iter6_reg;
        or_ln73_2_reg_1609_pp0_iter8_reg <= or_ln73_2_reg_1609_pp0_iter7_reg;
        or_ln73_2_reg_1609_pp0_iter9_reg <= or_ln73_2_reg_1609_pp0_iter8_reg;
        select_ln70_1_reg_1586_pp0_iter2_reg <= select_ln70_1_reg_1586_pp0_iter1_reg;
        select_ln70_1_reg_1586_pp0_iter3_reg <= select_ln70_1_reg_1586_pp0_iter2_reg;
        select_ln70_1_reg_1586_pp0_iter4_reg <= select_ln70_1_reg_1586_pp0_iter3_reg;
        select_ln70_1_reg_1586_pp0_iter5_reg <= select_ln70_1_reg_1586_pp0_iter4_reg;
        select_ln70_1_reg_1586_pp0_iter6_reg <= select_ln70_1_reg_1586_pp0_iter5_reg;
        select_ln70_1_reg_1586_pp0_iter7_reg <= select_ln70_1_reg_1586_pp0_iter6_reg;
        select_ln70_1_reg_1586_pp0_iter8_reg <= select_ln70_1_reg_1586_pp0_iter7_reg;
        select_ln70_2_reg_1591_pp0_iter2_reg <= select_ln70_2_reg_1591_pp0_iter1_reg;
        select_ln70_2_reg_1591_pp0_iter3_reg <= select_ln70_2_reg_1591_pp0_iter2_reg;
        select_ln70_2_reg_1591_pp0_iter4_reg <= select_ln70_2_reg_1591_pp0_iter3_reg;
        select_ln70_2_reg_1591_pp0_iter5_reg <= select_ln70_2_reg_1591_pp0_iter4_reg;
        select_ln70_2_reg_1591_pp0_iter6_reg <= select_ln70_2_reg_1591_pp0_iter5_reg;
        select_ln70_2_reg_1591_pp0_iter7_reg <= select_ln70_2_reg_1591_pp0_iter6_reg;
        select_ln70_2_reg_1591_pp0_iter8_reg <= select_ln70_2_reg_1591_pp0_iter7_reg;
        tmp_78_reg_1652 <= {{grp_fu_625_p2[68:66]}};
        tmp_79_reg_1657 <= {{grp_fu_625_p2[70:66]}};
        tmp_80_reg_1633_pp0_iter2_reg <= tmp_80_reg_1633;
        tmp_80_reg_1633_pp0_iter3_reg <= tmp_80_reg_1633_pp0_iter2_reg;
        tmp_80_reg_1633_pp0_iter4_reg <= tmp_80_reg_1633_pp0_iter3_reg;
        tmp_80_reg_1633_pp0_iter5_reg <= tmp_80_reg_1633_pp0_iter4_reg;
        tmp_80_reg_1633_pp0_iter6_reg <= tmp_80_reg_1633_pp0_iter5_reg;
        tmp_80_reg_1633_pp0_iter7_reg <= tmp_80_reg_1633_pp0_iter6_reg;
        tmp_80_reg_1633_pp0_iter8_reg <= tmp_80_reg_1633_pp0_iter7_reg;
        tmp_83_reg_1900 <= sub_ln78_fu_1379_p2[32'd16];
        tmp_84_reg_1915 <= sub_ln79_fu_1465_p2[32'd16];
        trunc_ln70_reg_1643 <= trunc_ln70_fu_905_p1;
        trunc_ln70_reg_1643_pp0_iter9_reg <= trunc_ln70_reg_1643;
        trunc_ln71_1_reg_1662 <= trunc_ln71_1_fu_929_p1;
        trunc_ln71_1_reg_1662_pp0_iter9_reg <= trunc_ln71_1_reg_1662;
        trunc_ln71_reg_1603_pp0_iter2_reg <= trunc_ln71_reg_1603_pp0_iter1_reg;
        trunc_ln71_reg_1603_pp0_iter3_reg <= trunc_ln71_reg_1603_pp0_iter2_reg;
        trunc_ln71_reg_1603_pp0_iter4_reg <= trunc_ln71_reg_1603_pp0_iter3_reg;
        trunc_ln71_reg_1603_pp0_iter5_reg <= trunc_ln71_reg_1603_pp0_iter4_reg;
        trunc_ln71_reg_1603_pp0_iter6_reg <= trunc_ln71_reg_1603_pp0_iter5_reg;
        trunc_ln71_reg_1603_pp0_iter7_reg <= trunc_ln71_reg_1603_pp0_iter6_reg;
        trunc_ln71_reg_1603_pp0_iter8_reg <= trunc_ln71_reg_1603_pp0_iter7_reg;
        trunc_ln78_1_reg_1905 <= {{sub_ln78_1_fu_1393_p2[16:1]}};
        trunc_ln78_2_reg_1910 <= {{sub_ln78_fu_1379_p2[16:1]}};
        trunc_ln79_1_reg_1920 <= {{sub_ln79_1_fu_1479_p2[16:1]}};
        trunc_ln79_2_reg_1925 <= {{sub_ln79_fu_1465_p2[16:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ap_phi_reg_pp0_iter10_storemerge_reg_613 <= ap_phi_reg_pp0_iter9_storemerge_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_storemerge_reg_613 <= ap_phi_reg_pp0_iter0_storemerge_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_storemerge_reg_613 <= ap_phi_reg_pp0_iter2_storemerge_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_storemerge_reg_613 <= ap_phi_reg_pp0_iter3_storemerge_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_storemerge_reg_613 <= ap_phi_reg_pp0_iter4_storemerge_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_reg_pp0_iter6_storemerge_reg_613 <= ap_phi_reg_pp0_iter5_storemerge_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_phi_reg_pp0_iter7_storemerge_reg_613 <= ap_phi_reg_pp0_iter6_storemerge_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_phi_reg_pp0_iter8_storemerge_reg_613 <= ap_phi_reg_pp0_iter7_storemerge_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ap_phi_reg_pp0_iter9_storemerge_reg_613 <= ap_phi_reg_pp0_iter8_storemerge_reg_613;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        It16_ce0_local = 1'b1;
    end else begin
        It16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        It16_we0_local = 1'b1;
    end else begin
        It16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        Ix16_ce0_local = 1'b1;
    end else begin
        Ix16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Ix16_ce1_local = 1'b1;
    end else begin
        Ix16_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (or_ln73_2_reg_1609_pp0_iter10_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter10_reg == 1'd0))) begin
        Ix16_we0_local = 1'b1;
    end else begin
        Ix16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln73_2_reg_1609 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln70_reg_1575 == 1'd0))) begin
        Ix16_we1_local = 1'b1;
    end else begin
        Ix16_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        Iy16_ce0_local = 1'b1;
    end else begin
        Iy16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Iy16_ce1_local = 1'b1;
    end else begin
        Iy16_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (or_ln73_2_reg_1609_pp0_iter10_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter10_reg == 1'd0))) begin
        Iy16_we0_local = 1'b1;
    end else begin
        Iy16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln73_2_reg_1609 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln70_reg_1575 == 1'd0))) begin
        Iy16_we1_local = 1'b1;
    end else begin
        Iy16_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_fu_705_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_144;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_load = 5'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 5'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_140;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        img2_16_ce0_local = 1'b1;
    end else begin
        img2_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1295)) begin
        if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0_local = zext_ln80_2_fu_1110_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0_local = zext_ln79_4_fu_1091_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0_local = zext_ln79_3_fu_1072_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0_local = zext_ln78_6_fu_1206_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0_local = zext_ln78_3_fu_1158_p1;
        end else begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0_local = 'bx;
        end
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 
    == 2'd0) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1295)) begin
        if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0_local = zext_ln80_2_fu_1110_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0_local = zext_ln79_4_fu_1091_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0_local = zext_ln79_3_fu_1072_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0_local = zext_ln78_6_fu_1206_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0_local = zext_ln78_3_fu_1158_p1;
        end else begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0_local = 'bx;
        end
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 
    == 2'd0) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1295)) begin
        if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0_local = zext_ln80_2_fu_1110_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0_local = zext_ln79_4_fu_1091_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0_local = zext_ln79_3_fu_1072_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0_local = zext_ln78_6_fu_1206_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0_local = zext_ln78_3_fu_1158_p1;
        end else begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0_local = 'bx;
        end
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 
    == 2'd0) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1295)) begin
        if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0_local = zext_ln80_2_fu_1110_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0_local = zext_ln79_4_fu_1091_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0_local = zext_ln79_3_fu_1072_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0_local = zext_ln78_6_fu_1206_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0_local = zext_ln78_3_fu_1158_p1;
        end else begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0_local = 'bx;
        end
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 
    == 2'd0) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1295)) begin
        if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0_local = zext_ln80_2_fu_1110_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0_local = zext_ln79_4_fu_1091_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0_local = zext_ln79_3_fu_1072_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0_local = zext_ln78_6_fu_1206_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0_local = zext_ln78_3_fu_1158_p1;
        end else begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0_local = 'bx;
        end
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 
    == 2'd0) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1295)) begin
        if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0_local = zext_ln80_2_fu_1110_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0_local = zext_ln79_4_fu_1091_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0_local = zext_ln79_3_fu_1072_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0_local = zext_ln78_6_fu_1206_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0_local = zext_ln78_3_fu_1158_p1;
        end else begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0_local = 'bx;
        end
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 
    == 2'd0) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1295)) begin
        if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0_local = zext_ln80_2_fu_1110_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0_local = zext_ln79_4_fu_1091_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0_local = zext_ln79_3_fu_1072_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0_local = zext_ln78_6_fu_1206_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0_local = zext_ln78_3_fu_1158_p1;
        end else begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0_local = 'bx;
        end
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 
    == 2'd0) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1295)) begin
        if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0_local = zext_ln80_2_fu_1110_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0_local = zext_ln79_4_fu_1091_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0_local = zext_ln79_3_fu_1072_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0_local = zext_ln78_6_fu_1206_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0_local = zext_ln78_3_fu_1158_p1;
        end else begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0_local = 'bx;
        end
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 
    == 2'd0) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1295)) begin
        if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0_local = zext_ln80_2_fu_1110_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0_local = zext_ln79_4_fu_1091_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0_local = zext_ln79_3_fu_1072_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd0) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0_local = zext_ln78_6_fu_1206_p1;
        end else if (((trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2))) begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0_local = zext_ln78_3_fu_1158_p1;
        end else begin
            p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0_local = 'bx;
        end
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd0) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd2) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 == 2'd1) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln71_1_reg_1662 
    == 2'd0) & (trunc_ln70_reg_1643 == 2'd2) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0)))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign It16_address0 = It16_addr_reg_1613_pp0_iter10_reg;

assign It16_ce0 = It16_ce0_local;

assign It16_d0 = ap_phi_reg_pp0_iter11_storemerge_reg_613;

assign It16_we0 = It16_we0_local;

assign Ix16_address0 = Ix16_addr_reg_1618_pp0_iter10_reg;

assign Ix16_address1 = zext_ln80_1_fu_864_p1;

assign Ix16_ce0 = Ix16_ce0_local;

assign Ix16_ce1 = Ix16_ce1_local;

assign Ix16_d0 = select_ln78_fu_1535_p3;

assign Ix16_d1 = 16'd0;

assign Ix16_we0 = Ix16_we0_local;

assign Ix16_we1 = Ix16_we1_local;

assign Iy16_address0 = Iy16_addr_reg_1623_pp0_iter10_reg;

assign Iy16_address1 = zext_ln80_1_fu_864_p1;

assign Iy16_ce0 = Iy16_ce0_local;

assign Iy16_ce1 = Iy16_ce1_local;

assign Iy16_d0 = select_ln79_fu_1547_p3;

assign Iy16_d1 = 16'd0;

assign Iy16_we0 = Iy16_we0_local;

assign Iy16_we1 = Iy16_we1_local;

assign add_ln70_fu_711_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln71_fu_827_p2 = (select_ln70_fu_729_p3 + 5'd1);

assign add_ln78_1_fu_1171_p2 = ($signed(trunc_ln71_reg_1603_pp0_iter8_reg) + $signed(4'd15));

assign add_ln78_2_fu_1152_p2 = (sub_ln70_fu_982_p2 + zext_ln78_2_fu_1148_p1);

assign add_ln78_3_fu_1200_p2 = (sub_ln70_fu_982_p2 + zext_ln78_5_fu_1196_p1);

assign add_ln78_fu_1123_p2 = (trunc_ln71_reg_1603_pp0_iter8_reg + 4'd1);

assign add_ln79_1_fu_891_p2 = ($signed(select_ln70_2_reg_1591_pp0_iter3_reg) + $signed(5'd31));

assign add_ln79_2_fu_743_p2 = (ap_sig_allocacmp_y_load + 5'd1);

assign add_ln79_3_fu_1066_p2 = (sub_ln79_3_fu_1037_p2 + zext_ln79_2_fu_1063_p1);

assign add_ln79_4_fu_1085_p2 = (sub_ln79_4_fu_1057_p2 + zext_ln79_2_fu_1063_p1);

assign add_ln79_fu_737_p2 = (ap_sig_allocacmp_y_load + 5'd2);

assign add_ln80_1_fu_1104_p2 = (sub_ln70_fu_982_p2 + zext_ln79_2_fu_1063_p1);

assign add_ln80_fu_858_p2 = (tmp_69_fu_848_p3 + zext_ln80_fu_855_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1295 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (or_ln73_2_reg_1609_pp0_iter8_reg == 1'd0) & (icmp_ln70_reg_1575_pp0_iter8_reg == 1'd0));
end

always @ (*) begin
    ap_condition_426 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_613 = 'bx;

assign ap_ready = ap_ready_sig;

assign grp_fu_625_p0 = grp_fu_625_p00;

assign grp_fu_625_p00 = $unsigned(sext_ln71_fu_896_p1);

assign grp_fu_625_p1 = 129'd24595658764946068822;

assign grp_fu_630_p7 = 'bx;

assign grp_fu_649_p7 = 'bx;

assign grp_fu_668_p7 = 'bx;

assign grp_fu_769_p1 = 5'd3;

assign grp_fu_791_p1 = 5'd3;

assign icmp_ln70_fu_705_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_723_p2 = ((ap_sig_allocacmp_x_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln73_1_fu_781_p2 = ((select_ln70_2_fu_757_p3 == 5'd15) ? 1'b1 : 1'b0);

assign icmp_ln73_2_fu_797_p2 = ((select_ln70_fu_729_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln73_3_fu_803_p2 = ((select_ln70_fu_729_p3 == 5'd15) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_775_p2 = ((select_ln70_2_fu_757_p3 == 5'd0) ? 1'b1 : 1'b0);

assign img2_16_address0 = img2_16_addr_reg_1628_pp0_iter8_reg;

assign img2_16_ce0 = img2_16_ce0_local;

assign mul_ln70_fu_936_p0 = mul_ln70_fu_936_p00;

assign mul_ln70_fu_936_p00 = select_ln70_2_reg_1591_pp0_iter8_reg;

assign mul_ln70_fu_936_p1 = 11'd43;

assign mul_ln71_1_fu_875_p0 = mul_ln71_1_fu_875_p00;

assign mul_ln71_1_fu_875_p00 = select_ln70_reg_1579;

assign mul_ln71_1_fu_875_p1 = 11'd43;

assign mul_ln78_1_fu_1180_p0 = mul_ln78_1_fu_1180_p00;

assign mul_ln78_1_fu_1180_p00 = add_ln78_1_fu_1171_p2;

assign mul_ln78_1_fu_1180_p1 = 9'd22;

assign mul_ln78_fu_1132_p0 = mul_ln78_fu_1132_p00;

assign mul_ln78_fu_1132_p00 = add_ln78_fu_1123_p2;

assign mul_ln78_fu_1132_p1 = 9'd22;

assign mul_ln79_fu_991_p0 = mul_ln79_fu_991_p00;

assign mul_ln79_fu_991_p00 = select_ln70_1_reg_1586_pp0_iter8_reg;

assign mul_ln79_fu_991_p1 = 11'd43;

assign or_ln73_1_fu_815_p2 = (icmp_ln73_fu_775_p2 | icmp_ln73_2_fu_797_p2);

assign or_ln73_2_fu_821_p2 = (or_ln73_fu_809_p2 | or_ln73_1_fu_815_p2);

assign or_ln73_fu_809_p2 = (icmp_ln73_3_fu_803_p2 | icmp_ln73_1_fu_781_p2);

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_address0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_10_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_address0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_11_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_address0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_12_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_address0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_13_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_address0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_14_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_address0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_15_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_address0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_16_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_address0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_17_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_address0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_9_ce0_local;

assign p_shl1_fu_1050_p3 = {{tmp_79_reg_1657}, {1'd0}};

assign p_shl_fu_1043_p3 = {{tmp_78_reg_1652}, {3'd0}};

assign select_ln70_1_fu_749_p3 = ((icmp_ln71_fu_723_p2[0:0] == 1'b1) ? add_ln79_fu_737_p2 : add_ln79_2_fu_743_p2);

assign select_ln70_2_fu_757_p3 = ((icmp_ln71_fu_723_p2[0:0] == 1'b1) ? add_ln79_2_fu_743_p2 : ap_sig_allocacmp_y_load);

assign select_ln70_fu_729_p3 = ((icmp_ln71_fu_723_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_x_load);

assign select_ln78_fu_1535_p3 = ((tmp_83_reg_1900[0:0] == 1'b1) ? sub_ln78_2_fu_1530_p2 : trunc_ln78_2_reg_1910);

assign select_ln79_fu_1547_p3 = ((tmp_84_reg_1915[0:0] == 1'b1) ? sub_ln79_2_fu_1542_p2 : trunc_ln79_2_reg_1925);

assign sext_ln71_fu_896_p1 = $signed(add_ln79_1_fu_891_p2);

assign sext_ln78_1_fu_1375_p1 = $signed(tmp_56_fu_1356_p9);

assign sext_ln78_fu_1295_p1 = $signed(tmp_52_fu_1276_p9);

assign sext_ln79_1_fu_1461_p1 = $signed(tmp_64_fu_1442_p9);

assign sext_ln79_fu_1438_p1 = $signed(tmp_60_fu_1419_p9);

assign sub_ln70_fu_982_p2 = (tmp_73_fu_970_p3 - zext_ln78_fu_978_p1);

assign sub_ln78_1_fu_1393_p2 = (17'd0 - sub_ln78_fu_1379_p2);

assign sub_ln78_2_fu_1530_p2 = (16'd0 - trunc_ln78_1_reg_1905);

assign sub_ln78_fu_1379_p2 = ($signed(sext_ln78_fu_1295_p1) - $signed(sext_ln78_1_fu_1375_p1));

assign sub_ln79_1_fu_1479_p2 = (17'd0 - sub_ln79_fu_1465_p2);

assign sub_ln79_2_fu_1542_p2 = (16'd0 - trunc_ln79_1_reg_1920);

assign sub_ln79_3_fu_1037_p2 = (tmp_77_fu_1025_p3 - zext_ln79_1_fu_1033_p1);

assign sub_ln79_4_fu_1057_p2 = (p_shl_fu_1043_p3 - p_shl1_fu_1050_p3);

assign sub_ln79_fu_1465_p2 = ($signed(sext_ln79_fu_1438_p1) - $signed(sext_ln79_1_fu_1461_p1));

assign sub_ln80_fu_1524_p2 = (img2_16_q0 - tmp_68_fu_1505_p9);

assign tmp_51_fu_1257_p7 = 'bx;

assign tmp_52_fu_1276_p7 = 'bx;

assign tmp_53_fu_1299_p7 = 'bx;

assign tmp_54_fu_1318_p7 = 'bx;

assign tmp_55_fu_1337_p7 = 'bx;

assign tmp_56_fu_1356_p7 = 'bx;

assign tmp_60_fu_1419_p7 = 'bx;

assign tmp_64_fu_1442_p7 = 'bx;

assign tmp_68_fu_1505_p7 = 'bx;

assign tmp_69_fu_848_p3 = {{trunc_ln80_reg_1598}, {4'd0}};

assign tmp_70_fu_942_p4 = {{mul_ln70_fu_936_p2[10:7]}};

assign tmp_71_fu_952_p4 = {{mul_ln70_fu_936_p2[9:7]}};

assign tmp_72_fu_962_p3 = {{tmp_70_fu_942_p4}, {1'd0}};

assign tmp_73_fu_970_p3 = {{tmp_71_fu_952_p4}, {3'd0}};

assign tmp_74_fu_997_p4 = {{mul_ln79_fu_991_p2[10:7]}};

assign tmp_75_fu_1007_p4 = {{mul_ln79_fu_991_p2[9:7]}};

assign tmp_76_fu_1017_p3 = {{tmp_74_fu_997_p4}, {1'd0}};

assign tmp_77_fu_1025_p3 = {{tmp_75_fu_1007_p4}, {3'd0}};

assign tmp_81_fu_1138_p4 = {{mul_ln78_fu_1132_p2[8:6]}};

assign tmp_82_fu_1186_p4 = {{mul_ln78_1_fu_1180_p2[8:6]}};

assign tmp_fu_1219_p7 = 'bx;

assign tmp_s_fu_1238_p7 = 'bx;

assign trunc_ln70_fu_905_p1 = grp_fu_769_p2[1:0];

assign trunc_ln71_1_fu_929_p1 = grp_fu_791_p2[1:0];

assign trunc_ln71_fu_787_p1 = select_ln70_fu_729_p3[3:0];

assign trunc_ln80_fu_765_p1 = select_ln70_2_fu_757_p3[3:0];

assign zext_ln78_2_fu_1148_p1 = tmp_81_fu_1138_p4;

assign zext_ln78_3_fu_1158_p1 = add_ln78_2_fu_1152_p2;

assign zext_ln78_5_fu_1196_p1 = tmp_82_fu_1186_p4;

assign zext_ln78_6_fu_1206_p1 = add_ln78_3_fu_1200_p2;

assign zext_ln78_fu_978_p1 = tmp_72_fu_962_p3;

assign zext_ln79_1_fu_1033_p1 = tmp_76_fu_1017_p3;

assign zext_ln79_2_fu_1063_p1 = tmp_80_reg_1633_pp0_iter8_reg;

assign zext_ln79_3_fu_1072_p1 = add_ln79_3_fu_1066_p2;

assign zext_ln79_4_fu_1091_p1 = add_ln79_4_fu_1085_p2;

assign zext_ln80_1_fu_864_p1 = add_ln80_fu_858_p2;

assign zext_ln80_2_fu_1110_p1 = add_ln80_1_fu_1104_p2;

assign zext_ln80_fu_855_p1 = select_ln70_reg_1579;

endmodule //pyramidal_hs_compute_derivatives_16
