-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pyramidal_hs_horn_schunck_64 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    u_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    u_ce0 : OUT STD_LOGIC;
    u_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    u_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    u_ce1 : OUT STD_LOGIC;
    u_we1 : OUT STD_LOGIC;
    u_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    u_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    v_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    v_ce0 : OUT STD_LOGIC;
    v_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    v_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    v_ce1 : OUT STD_LOGIC;
    v_we1 : OUT STD_LOGIC;
    v_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    v_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    Ix64_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    Ix64_ce0 : OUT STD_LOGIC;
    Ix64_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    Iy64_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    Iy64_ce0 : OUT STD_LOGIC;
    Iy64_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    It64_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    It64_ce0 : OUT STD_LOGIC;
    It64_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of pyramidal_hs_horn_schunck_64 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal iter_2_fu_128_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal iter_2_reg_182 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal v_load_reg_200 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal u_load_reg_205 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln37_fu_158_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln37_reg_210 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln37_1_fu_165_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln37_1_reg_215 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_start : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_done : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_idle : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_ready : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_ce0 : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_ce1 : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_we1 : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_ce0 : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_ce1 : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_we1 : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Ix64_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Ix64_ce0 : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Iy64_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Iy64_ce0 : STD_LOGIC;
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_It64_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_It64_ce0 : STD_LOGIC;
    signal y_reg_82 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln29_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln40_fu_148_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln31_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal iter_fu_52 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal v_ce0_local : STD_LOGIC;
    signal u_ce0_local : STD_LOGIC;
    signal tmp_fu_140_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pyramidal_hs_horn_schunck_64_Pipeline_VITIS_LOOP_33_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        u_load : IN STD_LOGIC_VECTOR (15 downto 0);
        v_load : IN STD_LOGIC_VECTOR (15 downto 0);
        y : IN STD_LOGIC_VECTOR (5 downto 0);
        add_ln37 : IN STD_LOGIC_VECTOR (5 downto 0);
        u_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        u_ce0 : OUT STD_LOGIC;
        u_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        u_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        u_ce1 : OUT STD_LOGIC;
        u_we1 : OUT STD_LOGIC;
        u_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        u_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        add_ln37_1 : IN STD_LOGIC_VECTOR (5 downto 0);
        v_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        v_ce0 : OUT STD_LOGIC;
        v_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        v_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        v_ce1 : OUT STD_LOGIC;
        v_we1 : OUT STD_LOGIC;
        v_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        v_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        Ix64_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        Ix64_ce0 : OUT STD_LOGIC;
        Ix64_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        Iy64_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        Iy64_ce0 : OUT STD_LOGIC;
        Iy64_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        It64_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        It64_ce0 : OUT STD_LOGIC;
        It64_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94 : component pyramidal_hs_horn_schunck_64_Pipeline_VITIS_LOOP_33_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_start,
        ap_done => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_done,
        ap_idle => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_idle,
        ap_ready => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_ready,
        u_load => u_load_reg_205,
        v_load => v_load_reg_200,
        y => y_reg_82,
        add_ln37 => add_ln37_reg_210,
        u_address0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_address0,
        u_ce0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_ce0,
        u_q0 => u_q0,
        u_address1 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_address1,
        u_ce1 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_ce1,
        u_we1 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_we1,
        u_d1 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_d1,
        u_q1 => u_q1,
        add_ln37_1 => add_ln37_1_reg_215,
        v_address0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_address0,
        v_ce0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_ce0,
        v_q0 => v_q0,
        v_address1 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_address1,
        v_ce1 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_ce1,
        v_we1 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_we1,
        v_d1 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_d1,
        v_q1 => v_q1,
        Ix64_address0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Ix64_address0,
        Ix64_ce0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Ix64_ce0,
        Ix64_q0 => Ix64_q0,
        Iy64_address0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Iy64_address0,
        Iy64_ce0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Iy64_ce0,
        Iy64_q0 => Iy64_q0,
        It64_address0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_It64_address0,
        It64_ce0 => grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_It64_ce0,
        It64_q0 => It64_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_ready = ap_const_logic_1)) then 
                    grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    iter_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                iter_fu_52 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln31_fu_134_p2 = ap_const_lv1_1))) then 
                iter_fu_52 <= iter_2_reg_182;
            end if; 
        end if;
    end process;

    y_reg_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_done = ap_const_logic_1))) then 
                y_reg_82 <= add_ln37_1_reg_215;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln29_fu_122_p2 = ap_const_lv1_0))) then 
                y_reg_82 <= ap_const_lv6_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln37_1_reg_215 <= add_ln37_1_fu_165_p2;
                add_ln37_reg_210 <= add_ln37_fu_158_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                iter_2_reg_182 <= iter_2_fu_128_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                u_load_reg_205 <= u_q0;
                v_load_reg_200 <= v_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_done, icmp_ln29_fu_122_p2, ap_CS_fsm_state6, icmp_ln31_fu_134_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln29_fu_122_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln31_fu_134_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    It64_address0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_It64_address0;
    It64_ce0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_It64_ce0;
    Ix64_address0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Ix64_address0;
    Ix64_ce0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Ix64_ce0;
    Iy64_address0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Iy64_address0;
    Iy64_ce0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_Iy64_ce0;
    add_ln37_1_fu_165_p2 <= std_logic_vector(unsigned(y_reg_82) + unsigned(ap_const_lv6_1));
    add_ln37_fu_158_p2 <= std_logic_vector(unsigned(y_reg_82) + unsigned(ap_const_lv6_3F));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_done)
    begin
        if ((grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln29_fu_122_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln29_fu_122_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln29_fu_122_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln29_fu_122_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_start <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_ap_start_reg;
    icmp_ln29_fu_122_p2 <= "1" when (iter_fu_52 = ap_const_lv3_5) else "0";
    icmp_ln31_fu_134_p2 <= "1" when (y_reg_82 = ap_const_lv6_3F) else "0";
    iter_2_fu_128_p2 <= std_logic_vector(unsigned(iter_fu_52) + unsigned(ap_const_lv3_1));
    tmp_fu_140_p3 <= (y_reg_82 & ap_const_lv6_0);

    u_address0_assign_proc : process(grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_address0, ap_CS_fsm_state6, zext_ln40_fu_148_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            u_address0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_address0;
        else 
            u_address0 <= zext_ln40_fu_148_p1(12 - 1 downto 0);
        end if; 
    end process;

    u_address1 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_address1;

    u_ce0_assign_proc : process(grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_ce0, ap_CS_fsm_state6, u_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            u_ce0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_ce0;
        else 
            u_ce0 <= u_ce0_local;
        end if; 
    end process;


    u_ce0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            u_ce0_local <= ap_const_logic_1;
        else 
            u_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    u_ce1_assign_proc : process(grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            u_ce1 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_ce1;
        else 
            u_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    u_d1 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_d1;

    u_we1_assign_proc : process(grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_we1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            u_we1 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_u_we1;
        else 
            u_we1 <= ap_const_logic_0;
        end if; 
    end process;


    v_address0_assign_proc : process(grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_address0, ap_CS_fsm_state6, zext_ln40_fu_148_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            v_address0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_address0;
        else 
            v_address0 <= zext_ln40_fu_148_p1(12 - 1 downto 0);
        end if; 
    end process;

    v_address1 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_address1;

    v_ce0_assign_proc : process(grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_ce0, ap_CS_fsm_state6, v_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            v_ce0 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_ce0;
        else 
            v_ce0 <= v_ce0_local;
        end if; 
    end process;


    v_ce0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            v_ce0_local <= ap_const_logic_1;
        else 
            v_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    v_ce1_assign_proc : process(grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            v_ce1 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_ce1;
        else 
            v_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    v_d1 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_d1;

    v_we1_assign_proc : process(grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_we1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            v_we1 <= grp_horn_schunck_64_Pipeline_VITIS_LOOP_33_5_fu_94_v_we1;
        else 
            v_we1 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln40_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_140_p3),64));
end behav;
