-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pyramidal_hs_pyramidal_hs_Pipeline_VITIS_LOOP_6_1_VITIS_LOOP_7_23 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    img2_ce0 : OUT STD_LOGIC;
    img2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    img2_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    img2_ce1 : OUT STD_LOGIC;
    img2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_ce0 : OUT STD_LOGIC;
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_we0 : OUT STD_LOGIC;
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_ce0 : OUT STD_LOGIC;
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_we0 : OUT STD_LOGIC;
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of pyramidal_hs_pyramidal_hs_Pipeline_VITIS_LOOP_6_1_VITIS_LOOP_7_23 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln6_reg_434 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln6_fu_163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln9_fu_209_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln9_reg_438 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln9_reg_438_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln7_fu_213_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln7_reg_445 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln7_reg_445_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln7_reg_449 : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln7_reg_449_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln9_1_fu_227_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln9_1_reg_454 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln9_fu_294_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln9_reg_470 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal select_ln10_fu_393_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln10_reg_485 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln9_1_fu_243_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln9_2_fu_260_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_3_fu_310_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln10_fu_325_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_fu_407_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_66 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln7_fu_265_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_load : STD_LOGIC_VECTOR (5 downto 0);
    signal y_fu_70 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln6_1_fu_201_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_y_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten6_fu_74 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln6_fu_169_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (10 downto 0);
    signal img2_ce1_local : STD_LOGIC;
    signal img2_address1_local : STD_LOGIC_VECTOR (11 downto 0);
    signal img2_ce0_local : STD_LOGIC;
    signal img2_address0_local : STD_LOGIC_VECTOR (11 downto 0);
    signal pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_we0_local : STD_LOGIC;
    signal pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_ce0_local : STD_LOGIC;
    signal pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_we0_local : STD_LOGIC;
    signal pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_ce0_local : STD_LOGIC;
    signal icmp_ln7_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln6_1_fu_181_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln6_fu_193_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_231_p5 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_fu_248_p5 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln9_1_fu_290_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln9_fu_286_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_3_fu_300_p5 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_4_fu_315_p5 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln9_2_fu_330_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln9_3_fu_333_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln9_1_fu_337_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln10_fu_343_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln10_fu_347_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln10_fu_361_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln10_4_fu_367_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_353_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln10_1_fu_377_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln10_5_fu_383_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_401_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pyramidal_hs_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pyramidal_hs_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten6_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln6_fu_163_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_74 <= add_ln6_fu_169_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_74 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    x_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln6_fu_163_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_66 <= add_ln7_fu_265_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_66 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    y_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln6_fu_163_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    y_fu_70 <= select_ln6_1_fu_201_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_70 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln9_reg_470 <= add_ln9_fu_294_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln6_reg_434 <= icmp_ln6_fu_163_p2;
                lshr_ln7_reg_449 <= select_ln6_fu_193_p3(4 downto 1);
                lshr_ln7_reg_449_pp0_iter1_reg <= lshr_ln7_reg_449;
                select_ln10_reg_485 <= select_ln10_fu_393_p3;
                trunc_ln7_reg_445 <= trunc_ln7_fu_213_p1;
                trunc_ln7_reg_445_pp0_iter1_reg <= trunc_ln7_reg_445;
                trunc_ln9_1_reg_454 <= trunc_ln9_1_fu_227_p1;
                trunc_ln9_reg_438 <= trunc_ln9_fu_209_p1;
                trunc_ln9_reg_438_pp0_iter1_reg <= trunc_ln9_reg_438;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln10_fu_347_p2 <= std_logic_vector(unsigned(add_ln9_1_fu_337_p2) + unsigned(sext_ln10_fu_343_p1));
    add_ln6_1_fu_181_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_y_load) + unsigned(ap_const_lv6_1));
    add_ln6_fu_169_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv11_1));
    add_ln7_fu_265_p2 <= std_logic_vector(unsigned(select_ln6_fu_193_p3) + unsigned(ap_const_lv6_1));
    add_ln9_1_fu_337_p2 <= std_logic_vector(signed(sext_ln9_2_fu_330_p1) + signed(sext_ln9_3_fu_333_p1));
    add_ln9_fu_294_p2 <= std_logic_vector(signed(sext_ln9_1_fu_290_p1) + signed(sext_ln9_fu_286_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln6_reg_434)
    begin
        if (((icmp_ln6_reg_434 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_74)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_74;
        end if; 
    end process;


    ap_sig_allocacmp_x_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_66, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_x_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_x_load <= x_fu_66;
        end if; 
    end process;


    ap_sig_allocacmp_y_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, y_fu_70)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_y_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_y_load <= y_fu_70;
        end if; 
    end process;

    icmp_ln6_fu_163_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv11_400) else "0";
    icmp_ln7_fu_187_p2 <= "1" when (ap_sig_allocacmp_x_load = ap_const_lv6_20) else "0";
    img2_address0 <= img2_address0_local;

    img2_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0, zext_ln9_2_fu_260_p1, ap_block_pp0_stage1, zext_ln10_fu_325_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            img2_address0_local <= zext_ln10_fu_325_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img2_address0_local <= zext_ln9_2_fu_260_p1(12 - 1 downto 0);
        else 
            img2_address0_local <= "XXXXXXXXXXXX";
        end if; 
    end process;

    img2_address1 <= img2_address1_local;

    img2_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, zext_ln9_1_fu_243_p1, ap_block_pp0_stage0, zext_ln9_3_fu_310_p1, ap_block_pp0_stage1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            img2_address1_local <= zext_ln9_3_fu_310_p1(12 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img2_address1_local <= zext_ln9_1_fu_243_p1(12 - 1 downto 0);
        else 
            img2_address1_local <= "XXXXXXXXXXXX";
        end if; 
    end process;

    img2_ce0 <= img2_ce0_local;

    img2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            img2_ce0_local <= ap_const_logic_1;
        else 
            img2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img2_ce1 <= img2_ce1_local;

    img2_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            img2_ce1_local <= ap_const_logic_1;
        else 
            img2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_address0 <= zext_ln9_fu_407_p1(9 - 1 downto 0);
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_ce0 <= pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_ce0_local;

    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_ce0_local <= ap_const_logic_1;
        else 
            pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_d0 <= select_ln10_reg_485;
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_we0 <= pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_we0_local;

    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, trunc_ln7_reg_445_pp0_iter1_reg, ap_block_pp0_stage1_11001)
    begin
        if (((trunc_ln7_reg_445_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_we0_local <= ap_const_logic_1;
        else 
            pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_address0 <= zext_ln9_fu_407_p1(9 - 1 downto 0);
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_ce0 <= pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_ce0_local;

    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_ce0_local <= ap_const_logic_1;
        else 
            pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_d0 <= select_ln10_reg_485;
    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_we0 <= pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_we0_local;

    pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, trunc_ln7_reg_445_pp0_iter1_reg, ap_block_pp0_stage1_11001)
    begin
        if (((trunc_ln7_reg_445_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_we0_local <= ap_const_logic_1;
        else 
            pyramidal_hs_ap_fixed_64_ap_fixed_64_ap_fixed_64_ap_fixed_64_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln10_fu_393_p3 <= 
        sub_ln10_1_fu_377_p2 when (tmp_fu_353_p3(0) = '1') else 
        trunc_ln10_5_fu_383_p4;
    select_ln6_1_fu_201_p3 <= 
        add_ln6_1_fu_181_p2 when (icmp_ln7_fu_187_p2(0) = '1') else 
        ap_sig_allocacmp_y_load;
    select_ln6_fu_193_p3 <= 
        ap_const_lv6_0 when (icmp_ln7_fu_187_p2(0) = '1') else 
        ap_sig_allocacmp_x_load;
        sext_ln10_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(img2_q0),18));

        sext_ln9_1_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(img2_q0),17));

        sext_ln9_2_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln9_reg_470),18));

        sext_ln9_3_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(img2_q1),18));

        sext_ln9_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(img2_q1),17));

    sub_ln10_1_fu_377_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(trunc_ln10_4_fu_367_p4));
    sub_ln10_fu_361_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(add_ln10_fu_347_p2));
    tmp_1_fu_231_p5 <= (((trunc_ln9_fu_209_p1 & ap_const_lv1_0) & trunc_ln9_1_fu_227_p1) & ap_const_lv1_0);
    tmp_2_fu_248_p5 <= (((trunc_ln9_fu_209_p1 & ap_const_lv1_1) & trunc_ln9_1_fu_227_p1) & ap_const_lv1_0);
    tmp_3_fu_300_p5 <= (((trunc_ln9_reg_438 & ap_const_lv1_0) & trunc_ln9_1_reg_454) & ap_const_lv1_1);
    tmp_4_fu_315_p5 <= (((trunc_ln9_reg_438 & ap_const_lv1_1) & trunc_ln9_1_reg_454) & ap_const_lv1_1);
    tmp_fu_353_p3 <= add_ln10_fu_347_p2(17 downto 17);
    tmp_s_fu_401_p3 <= (trunc_ln9_reg_438_pp0_iter1_reg & lshr_ln7_reg_449_pp0_iter1_reg);
    trunc_ln10_4_fu_367_p4 <= sub_ln10_fu_361_p2(17 downto 2);
    trunc_ln10_5_fu_383_p4 <= add_ln10_fu_347_p2(17 downto 2);
    trunc_ln7_fu_213_p1 <= select_ln6_fu_193_p3(1 - 1 downto 0);
    trunc_ln9_1_fu_227_p1 <= select_ln6_fu_193_p3(5 - 1 downto 0);
    trunc_ln9_fu_209_p1 <= select_ln6_1_fu_201_p3(5 - 1 downto 0);
    zext_ln10_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_315_p5),64));
    zext_ln9_1_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_231_p5),64));
    zext_ln9_2_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_248_p5),64));
    zext_ln9_3_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_300_p5),64));
    zext_ln9_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_401_p3),64));
end behav;
