// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module pyramidal_hs_pyramidal_hs_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_we0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_d0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_q0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_we0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_d0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_we0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_d0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_we0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_d0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_we0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_d0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_address0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_ce0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_we0,
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_ce0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_we0;
output  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_d0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_q0;
output  [5:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_ce0;
input  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_q0;
output  [7:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_ce0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_we0;
output  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_d0;
output  [7:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_ce0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_we0;
output  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_d0;
output  [7:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_ce0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_we0;
output  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_d0;
output  [7:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_ce0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_we0;
output  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_d0;
output  [7:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_address0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_ce0;
output   p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_we0;
output  [15:0] p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln29_fu_284_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] select_ln29_1_fu_322_p3;
reg   [3:0] trunc_ln32_4_reg_568;
reg   [3:0] trunc_ln32_4_reg_568_pp0_iter1_reg;
wire   [0:0] trunc_ln30_fu_356_p1;
reg   [0:0] trunc_ln30_reg_574;
reg   [0:0] trunc_ln30_reg_574_pp0_iter1_reg;
reg   [0:0] trunc_ln30_reg_574_pp0_iter2_reg;
reg   [0:0] trunc_ln30_reg_574_pp0_iter3_reg;
reg   [0:0] trunc_ln30_reg_574_pp0_iter4_reg;
reg   [0:0] trunc_ln30_reg_574_pp0_iter5_reg;
reg   [0:0] trunc_ln30_reg_574_pp0_iter6_reg;
reg   [0:0] trunc_ln30_reg_574_pp0_iter7_reg;
reg   [0:0] trunc_ln30_reg_574_pp0_iter8_reg;
reg   [3:0] lshr_ln_reg_578;
reg   [3:0] lshr_ln_reg_578_pp0_iter1_reg;
reg   [3:0] lshr_ln_reg_578_pp0_iter2_reg;
reg   [3:0] lshr_ln_reg_578_pp0_iter3_reg;
reg   [3:0] lshr_ln_reg_578_pp0_iter4_reg;
reg   [3:0] lshr_ln_reg_578_pp0_iter5_reg;
reg   [3:0] lshr_ln_reg_578_pp0_iter6_reg;
reg   [3:0] lshr_ln_reg_578_pp0_iter7_reg;
reg   [3:0] lshr_ln_reg_578_pp0_iter8_reg;
reg   [3:0] tmp_40_cast_reg_583;
reg   [3:0] tmp_40_cast_reg_583_pp0_iter1_reg;
reg   [3:0] tmp_40_cast_reg_583_pp0_iter2_reg;
reg   [3:0] tmp_40_cast_reg_583_pp0_iter3_reg;
reg   [3:0] tmp_40_cast_reg_583_pp0_iter4_reg;
reg   [3:0] tmp_40_cast_reg_583_pp0_iter5_reg;
reg   [3:0] tmp_40_cast_reg_583_pp0_iter6_reg;
reg   [3:0] tmp_40_cast_reg_583_pp0_iter7_reg;
reg   [3:0] tmp_40_cast_reg_583_pp0_iter8_reg;
reg   [2:0] lshr_ln32_2_reg_588;
reg   [2:0] lshr_ln32_2_reg_588_pp0_iter1_reg;
reg   [2:0] lshr_ln32_2_reg_588_pp0_iter2_reg;
reg   [2:0] lshr_ln32_2_reg_588_pp0_iter3_reg;
reg   [2:0] lshr_ln32_2_reg_588_pp0_iter4_reg;
reg   [2:0] lshr_ln32_2_reg_588_pp0_iter5_reg;
reg   [2:0] lshr_ln32_2_reg_588_pp0_iter6_reg;
reg   [2:0] lshr_ln32_2_reg_588_pp0_iter7_reg;
reg   [0:0] tmp_reg_593;
reg   [0:0] tmp_reg_593_pp0_iter1_reg;
reg   [0:0] tmp_reg_593_pp0_iter2_reg;
reg   [0:0] tmp_reg_593_pp0_iter3_reg;
reg   [0:0] tmp_reg_593_pp0_iter4_reg;
reg   [0:0] tmp_reg_593_pp0_iter5_reg;
reg   [0:0] tmp_reg_593_pp0_iter6_reg;
reg   [0:0] tmp_reg_593_pp0_iter7_reg;
reg   [0:0] tmp_reg_593_pp0_iter8_reg;
reg   [2:0] tmp_42_cast_reg_600;
reg   [2:0] tmp_42_cast_reg_600_pp0_iter3_reg;
reg   [2:0] tmp_42_cast_reg_600_pp0_iter4_reg;
reg   [2:0] tmp_42_cast_reg_600_pp0_iter5_reg;
reg   [2:0] tmp_42_cast_reg_600_pp0_iter6_reg;
reg   [2:0] tmp_42_cast_reg_600_pp0_iter7_reg;
wire   [63:0] zext_ln32_2_fu_449_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln32_1_fu_473_p1;
reg   [5:0] x_fu_98;
wire   [5:0] add_ln30_fu_398_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_x_load;
reg   [5:0] y_fu_102;
reg   [5:0] ap_sig_allocacmp_y_load;
reg   [10:0] indvar_flatten27_fu_106;
wire   [10:0] add_ln29_2_fu_290_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten27_load;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_we0_local;
wire   [1:0] trunc_ln29_fu_459_p1;
wire   [15:0] tmp_15_fu_504_p9;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_we0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_we0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_we0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_we0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_ce0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_we0_local;
reg    p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_ce0_local;
wire   [0:0] icmp_ln30_fu_308_p2;
wire   [5:0] add_ln29_fu_302_p2;
wire   [5:0] mul_ln29_fu_334_p0;
wire   [7:0] mul_ln29_fu_334_p1;
wire   [2:0] grp_fu_340_p1;
wire   [5:0] select_ln29_fu_314_p3;
wire   [12:0] mul_ln29_fu_334_p2;
wire   [3:0] mul_ln32_fu_422_p0;
wire   [5:0] mul_ln32_fu_422_p1;
wire   [2:0] grp_fu_428_p1;
wire   [8:0] mul_ln32_fu_422_p2;
wire   [5:0] tmp_16_fu_443_p3;
wire   [1:0] grp_fu_340_p2;
wire   [1:0] grp_fu_428_p2;
wire   [7:0] tmp_s_fu_467_p3;
wire   [15:0] tmp_15_fu_504_p2;
wire   [15:0] tmp_15_fu_504_p4;
wire   [15:0] tmp_15_fu_504_p6;
wire   [15:0] tmp_15_fu_504_p7;
wire   [1:0] tmp_15_fu_504_p8;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [12:0] mul_ln29_fu_334_p00;
wire   [8:0] mul_ln32_fu_422_p00;
wire   [1:0] tmp_15_fu_504_p1;
wire   [1:0] tmp_15_fu_504_p3;
wire  signed [1:0] tmp_15_fu_504_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 x_fu_98 = 6'd0;
#0 y_fu_102 = 6'd0;
#0 indvar_flatten27_fu_106 = 11'd0;
#0 ap_done_reg = 1'b0;
end

pyramidal_hs_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U176(
    .din0(mul_ln29_fu_334_p0),
    .din1(mul_ln29_fu_334_p1),
    .dout(mul_ln29_fu_334_p2)
);

pyramidal_hs_urem_6ns_3ns_2_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_6ns_3ns_2_10_1_U177(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln29_1_fu_322_p3),
    .din1(grp_fu_340_p1),
    .ce(1'b1),
    .dout(grp_fu_340_p2)
);

pyramidal_hs_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U178(
    .din0(mul_ln32_fu_422_p0),
    .din1(mul_ln32_fu_422_p1),
    .dout(mul_ln32_fu_422_p2)
);

pyramidal_hs_urem_4ns_3ns_2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_4ns_3ns_2_8_1_U179(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln32_4_reg_568_pp0_iter1_reg),
    .din1(grp_fu_428_p1),
    .ce(1'b1),
    .dout(grp_fu_428_p2)
);

(* dissolve_hierarchy = "yes" *) pyramidal_hs_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U180(
    .din0(tmp_15_fu_504_p2),
    .din1(tmp_15_fu_504_p4),
    .din2(tmp_15_fu_504_p6),
    .def(tmp_15_fu_504_p7),
    .sel(tmp_15_fu_504_p8),
    .dout(tmp_15_fu_504_p9)
);

pyramidal_hs_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln29_fu_284_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten27_fu_106 <= add_ln29_2_fu_290_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten27_fu_106 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln29_fu_284_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_98 <= add_ln30_fu_398_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_98 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln29_fu_284_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_102 <= select_ln29_1_fu_322_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_102 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        lshr_ln32_2_reg_588 <= {{select_ln29_fu_314_p3[4:2]}};
        lshr_ln32_2_reg_588_pp0_iter1_reg <= lshr_ln32_2_reg_588;
        lshr_ln_reg_578 <= {{select_ln29_fu_314_p3[4:1]}};
        lshr_ln_reg_578_pp0_iter1_reg <= lshr_ln_reg_578;
        tmp_40_cast_reg_583 <= {{mul_ln29_fu_334_p2[11:8]}};
        tmp_40_cast_reg_583_pp0_iter1_reg <= tmp_40_cast_reg_583;
        tmp_reg_593 <= select_ln29_fu_314_p3[32'd1];
        tmp_reg_593_pp0_iter1_reg <= tmp_reg_593;
        trunc_ln30_reg_574 <= trunc_ln30_fu_356_p1;
        trunc_ln30_reg_574_pp0_iter1_reg <= trunc_ln30_reg_574;
        trunc_ln32_4_reg_568 <= {{select_ln29_1_fu_322_p3[4:1]}};
        trunc_ln32_4_reg_568_pp0_iter1_reg <= trunc_ln32_4_reg_568;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        lshr_ln32_2_reg_588_pp0_iter2_reg <= lshr_ln32_2_reg_588_pp0_iter1_reg;
        lshr_ln32_2_reg_588_pp0_iter3_reg <= lshr_ln32_2_reg_588_pp0_iter2_reg;
        lshr_ln32_2_reg_588_pp0_iter4_reg <= lshr_ln32_2_reg_588_pp0_iter3_reg;
        lshr_ln32_2_reg_588_pp0_iter5_reg <= lshr_ln32_2_reg_588_pp0_iter4_reg;
        lshr_ln32_2_reg_588_pp0_iter6_reg <= lshr_ln32_2_reg_588_pp0_iter5_reg;
        lshr_ln32_2_reg_588_pp0_iter7_reg <= lshr_ln32_2_reg_588_pp0_iter6_reg;
        lshr_ln_reg_578_pp0_iter2_reg <= lshr_ln_reg_578_pp0_iter1_reg;
        lshr_ln_reg_578_pp0_iter3_reg <= lshr_ln_reg_578_pp0_iter2_reg;
        lshr_ln_reg_578_pp0_iter4_reg <= lshr_ln_reg_578_pp0_iter3_reg;
        lshr_ln_reg_578_pp0_iter5_reg <= lshr_ln_reg_578_pp0_iter4_reg;
        lshr_ln_reg_578_pp0_iter6_reg <= lshr_ln_reg_578_pp0_iter5_reg;
        lshr_ln_reg_578_pp0_iter7_reg <= lshr_ln_reg_578_pp0_iter6_reg;
        lshr_ln_reg_578_pp0_iter8_reg <= lshr_ln_reg_578_pp0_iter7_reg;
        tmp_40_cast_reg_583_pp0_iter2_reg <= tmp_40_cast_reg_583_pp0_iter1_reg;
        tmp_40_cast_reg_583_pp0_iter3_reg <= tmp_40_cast_reg_583_pp0_iter2_reg;
        tmp_40_cast_reg_583_pp0_iter4_reg <= tmp_40_cast_reg_583_pp0_iter3_reg;
        tmp_40_cast_reg_583_pp0_iter5_reg <= tmp_40_cast_reg_583_pp0_iter4_reg;
        tmp_40_cast_reg_583_pp0_iter6_reg <= tmp_40_cast_reg_583_pp0_iter5_reg;
        tmp_40_cast_reg_583_pp0_iter7_reg <= tmp_40_cast_reg_583_pp0_iter6_reg;
        tmp_40_cast_reg_583_pp0_iter8_reg <= tmp_40_cast_reg_583_pp0_iter7_reg;
        tmp_42_cast_reg_600 <= {{mul_ln32_fu_422_p2[8:6]}};
        tmp_42_cast_reg_600_pp0_iter3_reg <= tmp_42_cast_reg_600;
        tmp_42_cast_reg_600_pp0_iter4_reg <= tmp_42_cast_reg_600_pp0_iter3_reg;
        tmp_42_cast_reg_600_pp0_iter5_reg <= tmp_42_cast_reg_600_pp0_iter4_reg;
        tmp_42_cast_reg_600_pp0_iter6_reg <= tmp_42_cast_reg_600_pp0_iter5_reg;
        tmp_42_cast_reg_600_pp0_iter7_reg <= tmp_42_cast_reg_600_pp0_iter6_reg;
        tmp_reg_593_pp0_iter2_reg <= tmp_reg_593_pp0_iter1_reg;
        tmp_reg_593_pp0_iter3_reg <= tmp_reg_593_pp0_iter2_reg;
        tmp_reg_593_pp0_iter4_reg <= tmp_reg_593_pp0_iter3_reg;
        tmp_reg_593_pp0_iter5_reg <= tmp_reg_593_pp0_iter4_reg;
        tmp_reg_593_pp0_iter6_reg <= tmp_reg_593_pp0_iter5_reg;
        tmp_reg_593_pp0_iter7_reg <= tmp_reg_593_pp0_iter6_reg;
        tmp_reg_593_pp0_iter8_reg <= tmp_reg_593_pp0_iter7_reg;
        trunc_ln30_reg_574_pp0_iter2_reg <= trunc_ln30_reg_574_pp0_iter1_reg;
        trunc_ln30_reg_574_pp0_iter3_reg <= trunc_ln30_reg_574_pp0_iter2_reg;
        trunc_ln30_reg_574_pp0_iter4_reg <= trunc_ln30_reg_574_pp0_iter3_reg;
        trunc_ln30_reg_574_pp0_iter5_reg <= trunc_ln30_reg_574_pp0_iter4_reg;
        trunc_ln30_reg_574_pp0_iter6_reg <= trunc_ln30_reg_574_pp0_iter5_reg;
        trunc_ln30_reg_574_pp0_iter7_reg <= trunc_ln30_reg_574_pp0_iter6_reg;
        trunc_ln30_reg_574_pp0_iter8_reg <= trunc_ln30_reg_574_pp0_iter7_reg;
    end
end

always @ (*) begin
    if (((icmp_ln29_fu_284_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten27_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten27_load = indvar_flatten27_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_load = 6'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 6'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln29_fu_459_p1 == 2'd0) & ~(trunc_ln29_fu_459_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln30_reg_574_pp0_iter8_reg == 1'd1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_we0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln29_fu_459_p1 == 2'd0) & ~(trunc_ln29_fu_459_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln30_reg_574_pp0_iter8_reg == 1'd0))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_we0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln29_fu_459_p1 == 2'd1) & (trunc_ln30_reg_574_pp0_iter8_reg == 1'd1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_we0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln29_fu_459_p1 == 2'd1) & (trunc_ln30_reg_574_pp0_iter8_reg == 1'd0))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_we0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln29_fu_459_p1 == 2'd0) & (trunc_ln30_reg_574_pp0_iter8_reg == 1'd1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_we0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln29_fu_459_p1 == 2'd0) & (trunc_ln30_reg_574_pp0_iter8_reg == 1'd0))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_we0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_ce0_local = 1'b1;
    end else begin
        p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln29_2_fu_290_p2 = (ap_sig_allocacmp_indvar_flatten27_load + 11'd1);

assign add_ln29_fu_302_p2 = (ap_sig_allocacmp_y_load + 6'd1);

assign add_ln30_fu_398_p2 = (select_ln29_fu_314_p3 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_340_p1 = 6'd3;

assign grp_fu_428_p1 = 4'd3;

assign icmp_ln29_fu_284_p2 = ((ap_sig_allocacmp_indvar_flatten27_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_308_p2 = ((ap_sig_allocacmp_x_load == 6'd32) ? 1'b1 : 1'b0);

assign mul_ln29_fu_334_p0 = mul_ln29_fu_334_p00;

assign mul_ln29_fu_334_p00 = select_ln29_1_fu_322_p3;

assign mul_ln29_fu_334_p1 = 13'd86;

assign mul_ln32_fu_422_p0 = mul_ln32_fu_422_p00;

assign mul_ln32_fu_422_p00 = trunc_ln32_4_reg_568_pp0_iter1_reg;

assign mul_ln32_fu_422_p1 = 9'd22;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_address0 = zext_ln32_1_fu_473_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_d0 = tmp_15_fu_504_p9;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_we0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_30_we0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_address0 = zext_ln32_1_fu_473_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_d0 = tmp_15_fu_504_p9;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_we0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_31_we0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_address0 = zext_ln32_1_fu_473_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_d0 = tmp_15_fu_504_p9;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_we0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_32_we0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_address0 = zext_ln32_1_fu_473_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_d0 = tmp_15_fu_504_p9;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_we0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_33_we0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_address0 = zext_ln32_1_fu_473_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_d0 = tmp_15_fu_504_p9;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_we0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_34_we0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_address0 = zext_ln32_1_fu_473_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_d0 = tmp_15_fu_504_p9;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_we0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_35_we0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_address0 = zext_ln32_2_fu_449_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_address0 = zext_ln32_2_fu_449_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_address0 = zext_ln32_2_fu_449_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_address0 = zext_ln32_2_fu_449_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_address0 = zext_ln32_2_fu_449_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_ce0_local;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_address0 = zext_ln32_2_fu_449_p1;

assign p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_ce0 = p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_ce0_local;

assign select_ln29_1_fu_322_p3 = ((icmp_ln30_fu_308_p2[0:0] == 1'b1) ? add_ln29_fu_302_p2 : ap_sig_allocacmp_y_load);

assign select_ln29_fu_314_p3 = ((icmp_ln30_fu_308_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_x_load);

assign tmp_15_fu_504_p2 = ((tmp_reg_593_pp0_iter8_reg[0:0] == 1'b1) ? p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_40_q0 : p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_41_q0);

assign tmp_15_fu_504_p4 = ((tmp_reg_593_pp0_iter8_reg[0:0] == 1'b1) ? p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_38_q0 : p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_39_q0);

assign tmp_15_fu_504_p6 = ((tmp_reg_593_pp0_iter8_reg[0:0] == 1'b1) ? p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_36_q0 : p_ZZ12pyramidal_hsPA64_8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_mode3ELi0EES4_S4_S4_37_q0);

assign tmp_15_fu_504_p7 = 'bx;

assign tmp_15_fu_504_p8 = grp_fu_428_p2[1:0];

assign tmp_16_fu_443_p3 = {{tmp_42_cast_reg_600_pp0_iter7_reg}, {lshr_ln32_2_reg_588_pp0_iter7_reg}};

assign tmp_s_fu_467_p3 = {{tmp_40_cast_reg_583_pp0_iter8_reg}, {lshr_ln_reg_578_pp0_iter8_reg}};

assign trunc_ln29_fu_459_p1 = grp_fu_340_p2[1:0];

assign trunc_ln30_fu_356_p1 = select_ln29_fu_314_p3[0:0];

assign zext_ln32_1_fu_473_p1 = tmp_s_fu_467_p3;

assign zext_ln32_2_fu_449_p1 = tmp_16_fu_443_p3;

endmodule //pyramidal_hs_pyramidal_hs_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2
